import type { IconNode } from "lucide";
// A few icon names collide with globals this module uses (`Map` is the
// constructor below) or with names a module may not shadow (`Infinity`); those
// arrive under an `*Icon` alias.
import {
  Activity,
  AlarmClock,
  Anchor,
  Apple,
  Archive,
  ArchiveRestore,
  Armchair,
  ArrowRight,
  Asterisk,
  Atom,
  AtSign,
  AudioLines,
  Award,
  Baby,
  Backpack,
  BadgeAlert,
  BadgeCheck,
  BadgeDollarSign,
  BadgeEuro,
  BadgeInfo,
  Banknote,
  BanknoteArrowDown,
  BanknoteArrowUp,
  Bath,
  Battery,
  Bed,
  Beer,
  Bell,
  BellOff,
  BellRing,
  Bike,
  Binary,
  Bird,
  Bitcoin,
  Book,
  Bookmark,
  BookmarkCheck,
  BookMarked,
  BookmarkPlus,
  BookOpen,
  BookUser,
  Bot,
  Box,
  Braces,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  Camera,
  Candy,
  Car,
  CarFront,
  Carrot,
  Castle,
  Cat,
  ChartArea,
  ChartBar,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChartScatter,
  Check,
  ChefHat,
  Cherry,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDollarSign,
  CircleDot,
  CircleMinus,
  CirclePlay,
  CirclePlus,
  CircleQuestionMark,
  CircleUserRound,
  CircleX,
  Clapperboard,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudCog,
  CloudDownload,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudSnow,
  CloudSun,
  CloudUpload,
  Code,
  CodeXml,
  Coffee,
  Coins,
  Compass,
  Contact,
  Contrast,
  Copy,
  Cpu,
  CreditCard,
  Crop,
  Crown,
  Database,
  Diamond,
  Dna,
  Dog,
  DollarSign,
  DoorOpen,
  Droplet,
  Droplets,
  Dumbbell,
  Earth,
  Euro,
  ExternalLink,
  Eye,
  EyeOff,
  Feather,
  FerrisWheel,
  File,
  FileArchive,
  FileChartColumn,
  FileCheck,
  FileCode,
  FileImage,
  FileLock,
  FilePen,
  FilePlus,
  FileQuestionMark,
  Files,
  FileSearch,
  FileSpreadsheet,
  FileTerminal,
  FileText,
  Film,
  FingerprintPattern,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower,
  Folder,
  FolderGit2,
  FolderKanban,
  FolderLock,
  FolderOpen,
  FolderPlus,
  Folders,
  FolderSearch,
  FolderTree,
  Forward,
  Frame,
  Fuel,
  Funnel,
  Gamepad2,
  Gavel,
  Ghost,
  Gift,
  GitBranch,
  GitMerge,
  Globe,
  GraduationCap,
  Grape,
  Grip,
  Guitar,
  Hammer,
  Hand,
  HandCoins,
  Handshake,
  HardDrive,
  Hash,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Hexagon,
  Highlighter,
  History,
  Hotel,
  Hourglass,
  House,
  HousePlus,
  IceCreamCone,
  IdCard,
  Image,
  ImagePlus,
  Images,
  Inbox,
  Infinity as InfinityIcon,
  Info,
  Kanban,
  Key,
  Keyboard,
  Landmark,
  Languages,
  Laptop,
  Layers,
  LayoutDashboard,
  Leaf,
  Library,
  LibraryBig,
  Lightbulb,
  Link,
  List,
  ListChecks,
  ListFilter,
  ListMusic,
  ListOrdered,
  ListTodo,
  ListTree,
  LocateFixed,
  Lock,
  LockOpen,
  Luggage,
  Mail,
  MailCheck,
  MailOpen,
  MailPlus,
  Mails,
  Map as MapIcon,
  MapPin,
  MapPinned,
  Maximize2,
  Medal,
  Megaphone,
  MessageCircle,
  MessageCircleMore,
  MessageSquare,
  MessagesSquare,
  Mic,
  Microchip,
  Milestone,
  Minimize2,
  Monitor,
  Moon,
  Mountain,
  MountainSnow,
  Music,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  NotebookTabs,
  NotebookText,
  NotepadText,
  OctagonAlert,
  Package,
  Paintbrush,
  PaintBucket,
  Palette,
  Paperclip,
  PartyPopper,
  Pause,
  PawPrint,
  Pen,
  Pencil,
  PenTool,
  Percent,
  Phone,
  PhoneCall,
  PiggyBank,
  Pill,
  Pin,
  Pipette,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Play,
  Plug,
  Presentation,
  Printer,
  Puzzle,
  QrCode,
  Quote,
  Rabbit,
  Rainbow,
  Receipt,
  ReceiptText,
  Recycle,
  RefreshCw,
  Reply,
  ReplyAll,
  Rocket,
  RotateCcw,
  Route,
  Router,
  Rss,
  Sailboat,
  Salad,
  Sandwich,
  Scale,
  Scan,
  ScanFace,
  School,
  Scissors,
  ScrollText,
  Search,
  Send,
  SendHorizontal,
  Server,
  Settings,
  Shapes,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Signature,
  Signpost,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Snowflake,
  Sofa,
  Soup,
  Sparkles,
  Speech,
  SpellCheck,
  Sprout,
  SquareCheck,
  SquareCheckBig,
  SquareTerminal,
  Squirrel,
  Stamp,
  Star,
  Stethoscope,
  StickyNote,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Table,
  Tablet,
  Tag,
  Target,
  Telescope,
  Tent,
  Terminal,
  TestTube,
  TextQuote,
  Thermometer,
  ThumbsUp,
  Tickets,
  Timer,
  ToggleRight,
  Tornado,
  TrainFront,
  TramFront,
  Trash2,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  TrendingDown,
  TrendingUp,
  Triangle,
  TriangleAlert,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Type,
  Umbrella,
  User,
  UserCheck,
  UserPlus,
  UserRound,
  Users,
  UsersRound,
  Utensils,
  Vault,
  Video,
  Volume2,
  VolumeX,
  Wallet,
  WandSparkles,
  Watch,
  Wifi,
  Wind,
  Wine,
  Workflow,
  Wrench,
  Zap,
} from "lucide";

/**
 * The curated icon set behind `lucide:<name>` document icons.
 *
 * lucide ships ~1,750 icons; offering all of them would be a wall, not a choice
 * (decision E2, report 2026-07-29), so this is a curated 400 — enough that
 * most notes find their icon, few enough that browsing works. From that size on,
 * **categories are not a comfort but a requirement**: they live as a field on
 * every entry so the search and the picker's tabs read from ONE source.
 */
export type LucideIconCategory = "knowledge" | "work" | "tech" | "people" | "media" | "life" | "nature" | "travel" | "finance" | "symbols";

/** The tab order of the picker; every category carries entries (see the test). */
export const LUCIDE_CATEGORIES: LucideIconCategory[] = [
  "knowledge",
  "work",
  "tech",
  "people",
  "media",
  "life",
  "nature",
  "travel",
  "finance",
  "symbols",
];

export interface LucideIconEntry {
  name: string;
  category: LucideIconCategory;
  keywords?: string[];
  node: IconNode;
}

// `name` is the official lucide kebab-case id. It is persisted in user files as
// `lucide:<name>`, so entries must keep the exact upstream naming — and an entry
// is never removed, or a note that uses it would lose its icon.
export const LUCIDE_ICONS: LucideIconEntry[] = [
  // Knowledge & files
  { name: "book", category: "knowledge", keywords: ["knowledge", "reading", "buch"], node: Book },
  { name: "book-open", category: "knowledge", keywords: ["reading", "study", "buch"], node: BookOpen },
  { name: "notebook", category: "knowledge", keywords: ["journal", "notes", "notizbuch"], node: Notebook },
  { name: "notebook-pen", category: "knowledge", keywords: ["journal", "writing", "notizen"], node: NotebookPen },
  { name: "library", category: "knowledge", keywords: ["books", "collection", "bibliothek"], node: Library },
  { name: "folder", category: "knowledge", keywords: ["directory", "ordner"], node: Folder },
  { name: "folder-open", category: "knowledge", keywords: ["directory", "ordner"], node: FolderOpen },
  { name: "folder-tree", category: "knowledge", keywords: ["structure", "hierarchy", "ordner"], node: FolderTree },
  { name: "file", category: "knowledge", keywords: ["document", "datei"], node: File },
  { name: "file-text", category: "knowledge", keywords: ["document", "note", "datei"], node: FileText },
  { name: "files", category: "knowledge", keywords: ["documents", "copies", "dateien"], node: Files },
  { name: "archive", category: "knowledge", keywords: ["box", "storage", "archiv"], node: Archive },
  { name: "newspaper", category: "knowledge", keywords: ["news", "press", "zeitung"], node: Newspaper },
  { name: "sticky-note", category: "knowledge", keywords: ["memo", "post-it", "notiz"], node: StickyNote },
  { name: "clipboard", category: "knowledge", keywords: ["paste", "zwischenablage"], node: Clipboard },
  { name: "clipboard-list", category: "knowledge", keywords: ["tasks", "checklist", "liste"], node: ClipboardList },
  { name: "search", category: "knowledge", keywords: ["find", "magnifier", "suche"], node: Search },
  { name: "bookmark", category: "knowledge", keywords: ["save", "favorite", "lesezeichen"], node: Bookmark },
  { name: "tag", category: "knowledge", keywords: ["label", "category", "etikett"], node: Tag },
  { name: "link", category: "knowledge", keywords: ["url", "chain", "verknuepfung"], node: Link },
  { name: "paperclip", category: "knowledge", keywords: ["attachment", "anhang", "bueroklammer"], node: Paperclip },
  { name: "graduation-cap", category: "knowledge", keywords: ["education", "university", "studium", "abschluss"], node: GraduationCap },
  { name: "brain", category: "knowledge", keywords: ["mind", "think", "gehirn"], node: Brain },
  { name: "school", category: "knowledge", keywords: ["education", "learning", "schule"], node: School },
  { name: "flask-conical", category: "knowledge", keywords: ["chemistry", "lab", "science", "chemie", "labor"], node: FlaskConical },
  { name: "dna", category: "knowledge", keywords: ["genetics", "biology", "gene"], node: Dna },
  { name: "book-marked", category: "knowledge", keywords: ["reading", "bookmark", "buch", "lesezeichen"], node: BookMarked },
  { name: "notebook-tabs", category: "knowledge", keywords: ["journal", "sections", "notizbuch", "register"], node: NotebookTabs },
  { name: "notebook-text", category: "knowledge", keywords: ["journal", "writing", "notizbuch", "text"], node: NotebookText },
  { name: "scroll-text", category: "knowledge", keywords: ["document", "parchment", "schriftrolle"], node: ScrollText },
  { name: "file-plus", category: "knowledge", keywords: ["new", "document", "neue", "datei"], node: FilePlus },
  { name: "file-pen", category: "knowledge", keywords: ["edit", "document", "datei", "bearbeiten"], node: FilePen },
  { name: "file-check", category: "knowledge", keywords: ["approved", "document", "datei", "geprueft"], node: FileCheck },
  { name: "file-search", category: "knowledge", keywords: ["find", "in", "document", "datei", "suchen"], node: FileSearch },
  { name: "file-code", category: "knowledge", keywords: ["source", "file", "quelldatei"], node: FileCode },
  { name: "file-spreadsheet", category: "knowledge", keywords: ["table", "excel", "tabelle"], node: FileSpreadsheet },
  { name: "file-image", category: "knowledge", keywords: ["picture", "file", "bilddatei"], node: FileImage },
  { name: "file-archive", category: "knowledge", keywords: ["zip", "compressed", "archiv"], node: FileArchive },
  { name: "file-lock", category: "knowledge", keywords: ["protected", "document", "datei", "geschuetzt"], node: FileLock },
  { name: "file-question-mark", category: "knowledge", keywords: ["unknown", "document", "datei", "frage"], node: FileQuestionMark },
  { name: "folder-plus", category: "knowledge", keywords: ["new", "folder", "neuer", "ordner"], node: FolderPlus },
  { name: "folder-search", category: "knowledge", keywords: ["find", "folder", "ordner", "suchen"], node: FolderSearch },
  { name: "folder-lock", category: "knowledge", keywords: ["protected", "folder", "ordner", "geschuetzt"], node: FolderLock },
  { name: "folder-git-2", category: "knowledge", keywords: ["repository", "projektordner"], node: FolderGit2 },
  { name: "folders", category: "knowledge", keywords: ["directories", "ordner"], node: Folders },
  { name: "bookmark-check", category: "knowledge", keywords: ["saved", "lesezeichen", "erledigt"], node: BookmarkCheck },
  { name: "bookmark-plus", category: "knowledge", keywords: ["save", "lesezeichen", "hinzufuegen"], node: BookmarkPlus },
  { name: "library-big", category: "knowledge", keywords: ["shelf", "collection", "regal", "bibliothek"], node: LibraryBig },
  { name: "text-quote", category: "knowledge", keywords: ["citation", "zitat"], node: TextQuote },
  { name: "quote", category: "knowledge", keywords: ["citation", "zitat"], node: Quote },
  { name: "type", category: "knowledge", keywords: ["typography", "font", "schrift"], node: Type },
  { name: "languages", category: "knowledge", keywords: ["translate", "sprachen", "uebersetzen"], node: Languages },
  { name: "spell-check", category: "knowledge", keywords: ["proofread", "rechtschreibung"], node: SpellCheck },
  { name: "highlighter", category: "knowledge", keywords: ["marker", "textmarker"], node: Highlighter },
  { name: "list-tree", category: "knowledge", keywords: ["outline", "hierarchy", "gliederung"], node: ListTree },
  { name: "hash", category: "knowledge", keywords: ["tag", "number", "raute"], node: Hash },
  { name: "binary", category: "knowledge", keywords: ["data", "bits", "binaer"], node: Binary },
  // Work & productivity
  { name: "briefcase", category: "work", keywords: ["work", "business", "job", "arbeit"], node: Briefcase },
  { name: "calendar", category: "work", keywords: ["date", "schedule", "kalender"], node: Calendar },
  { name: "calendar-days", category: "work", keywords: ["date", "month", "kalender"], node: CalendarDays },
  { name: "clock", category: "work", keywords: ["time", "watch", "uhr"], node: Clock },
  { name: "timer", category: "work", keywords: ["stopwatch", "countdown", "zeit"], node: Timer },
  { name: "target", category: "work", keywords: ["goal", "aim", "ziel"], node: Target },
  { name: "flag", category: "work", keywords: ["milestone", "marker", "flagge"], node: Flag },
  { name: "check", category: "work", keywords: ["done", "tick", "erledigt"], node: Check },
  { name: "circle-check", category: "work", keywords: ["done", "complete", "erledigt"], node: CircleCheck },
  { name: "list", category: "work", keywords: ["items", "bullets", "liste"], node: List },
  { name: "list-todo", category: "work", keywords: ["tasks", "checklist", "aufgaben"], node: ListTodo },
  { name: "kanban", category: "work", keywords: ["board", "columns", "projekt"], node: Kanban },
  { name: "layout-dashboard", category: "work", keywords: ["overview", "panels", "uebersicht"], node: LayoutDashboard },
  { name: "table", category: "work", keywords: ["grid", "spreadsheet", "tabelle"], node: Table },
  { name: "presentation", category: "work", keywords: ["slides", "meeting", "praesentation"], node: Presentation },
  { name: "inbox", category: "work", keywords: ["tray", "incoming", "eingang"], node: Inbox },
  { name: "send", category: "work", keywords: ["paper-plane", "submit", "senden"], node: Send },
  { name: "box", category: "work", keywords: ["package", "container", "kiste"], node: Box },
  { name: "package", category: "work", keywords: ["box", "delivery", "paket"], node: Package },
  { name: "calendar-check", category: "work", keywords: ["scheduled", "kalender", "erledigt"], node: CalendarCheck },
  { name: "calendar-clock", category: "work", keywords: ["deadline", "kalender", "uhr"], node: CalendarClock },
  { name: "calendar-plus", category: "work", keywords: ["new", "event", "kalender", "hinzufuegen"], node: CalendarPlus },
  { name: "calendar-range", category: "work", keywords: ["period", "zeitraum", "kalender"], node: CalendarRange },
  { name: "alarm-clock", category: "work", keywords: ["reminder", "wecker", "alarm"], node: AlarmClock },
  { name: "hourglass", category: "work", keywords: ["waiting", "duration", "sanduhr"], node: Hourglass },
  { name: "activity", category: "work", keywords: ["pulse", "metrics", "aktivitaet"], node: Activity },
  { name: "square-check-big", category: "work", keywords: ["checkbox", "done", "haekchen", "erledigt"], node: SquareCheckBig },
  { name: "square-check", category: "work", keywords: ["checkbox", "erledigt", "kaestchen"], node: SquareCheck },
  { name: "circle-dashed", category: "work", keywords: ["pending", "open", "offen"], node: CircleDashed },
  { name: "circle-dot", category: "work", keywords: ["in", "progress", "in", "arbeit"], node: CircleDot },
  { name: "list-checks", category: "work", keywords: ["checklist", "aufgaben", "liste"], node: ListChecks },
  { name: "list-ordered", category: "work", keywords: ["numbered", "nummeriert", "liste"], node: ListOrdered },
  { name: "list-filter", category: "work", keywords: ["filter", "sort", "filtern"], node: ListFilter },
  { name: "notepad-text", category: "work", keywords: ["notes", "memo", "notizblock"], node: NotepadText },
  { name: "receipt", category: "work", keywords: ["invoice", "bill", "rechnung", "beleg"], node: Receipt },
  { name: "signature", category: "work", keywords: ["sign", "unterschrift"], node: Signature },
  { name: "stamp", category: "work", keywords: ["approve", "stempel"], node: Stamp },
  { name: "pin", category: "work", keywords: ["pinned", "angepinnt"], node: Pin },
  { name: "milestone", category: "work", keywords: ["goal", "step", "meilenstein"], node: Milestone },
  { name: "route", category: "work", keywords: ["path", "plan", "weg", "route"], node: Route },
  { name: "workflow", category: "work", keywords: ["process", "pipeline", "ablauf"], node: Workflow },
  { name: "git-merge", category: "work", keywords: ["merge", "review", "zusammenfuehren"], node: GitMerge },
  { name: "users-round", category: "work", keywords: ["team", "meeting", "gruppe"], node: UsersRound },
  { name: "handshake", category: "work", keywords: ["deal", "agreement", "vereinbarung"], node: Handshake },
  { name: "scale", category: "work", keywords: ["balance", "decision", "waage"], node: Scale },
  { name: "gavel", category: "work", keywords: ["law", "decision", "hammer", "recht"], node: Gavel },
  { name: "folder-kanban", category: "work", keywords: ["project", "board", "projekt"], node: FolderKanban },
  { name: "building-2", category: "work", keywords: ["company", "office", "firma", "buero"], node: Building2 },
  { name: "truck", category: "work", keywords: ["delivery", "logistics", "lieferung"], node: Truck },
  // Tech
  { name: "code", category: "tech", keywords: ["programming", "developer", "quellcode"], node: Code },
  { name: "terminal", category: "tech", keywords: ["console", "shell", "command"], node: Terminal },
  { name: "cpu", category: "tech", keywords: ["chip", "processor", "prozessor"], node: Cpu },
  { name: "database", category: "tech", keywords: ["storage", "sql", "datenbank"], node: Database },
  { name: "server", category: "tech", keywords: ["host", "backend"], node: Server },
  { name: "hard-drive", category: "tech", keywords: ["disk", "storage", "festplatte"], node: HardDrive },
  { name: "monitor", category: "tech", keywords: ["screen", "display", "bildschirm"], node: Monitor },
  { name: "laptop", category: "tech", keywords: ["computer", "notebook"], node: Laptop },
  { name: "smartphone", category: "tech", keywords: ["phone", "mobile", "handy"], node: Smartphone },
  { name: "keyboard", category: "tech", keywords: ["typing", "keys", "tastatur"], node: Keyboard },
  { name: "globe", category: "tech", keywords: ["world", "internet", "web", "welt"], node: Globe },
  { name: "cloud", category: "tech", keywords: ["weather", "hosting", "wolke"], node: Cloud },
  { name: "wifi", category: "tech", keywords: ["wireless", "network", "wlan"], node: Wifi },
  { name: "bug", category: "tech", keywords: ["insect", "debug", "fehler", "kaefer"], node: Bug },
  { name: "bot", category: "tech", keywords: ["robot", "ai", "roboter"], node: Bot },
  { name: "git-branch", category: "tech", keywords: ["version", "fork", "zweig"], node: GitBranch },
  { name: "code-xml", category: "tech", keywords: ["markup", "html", "quellcode"], node: CodeXml },
  { name: "square-terminal", category: "tech", keywords: ["shell", "command", "konsole"], node: SquareTerminal },
  { name: "braces", category: "tech", keywords: ["json", "object", "klammern"], node: Braces },
  { name: "file-terminal", category: "tech", keywords: ["script", "skript"], node: FileTerminal },
  { name: "cloud-cog", category: "tech", keywords: ["infrastructure", "cloud", "einstellungen"], node: CloudCog },
  { name: "cloud-upload", category: "tech", keywords: ["sync", "upload", "hochladen"], node: CloudUpload },
  { name: "cloud-download", category: "tech", keywords: ["sync", "download", "herunterladen"], node: CloudDownload },
  { name: "network", category: "tech", keywords: ["topology", "netzwerk"], node: Network },
  { name: "router", category: "tech", keywords: ["wifi", "network", "router"], node: Router },
  { name: "plug", category: "tech", keywords: ["power", "connect", "stecker"], node: Plug },
  { name: "battery", category: "tech", keywords: ["power", "akku", "batterie"], node: Battery },
  { name: "microchip", category: "tech", keywords: ["processor", "chip"], node: Microchip },
  { name: "tablet", category: "tech", keywords: ["device", "tablet"], node: Tablet },
  { name: "watch", category: "tech", keywords: ["wearable", "uhr", "smartwatch"], node: Watch },
  { name: "printer", category: "tech", keywords: ["print", "drucker"], node: Printer },
  { name: "scan", category: "tech", keywords: ["scanner", "scannen"], node: Scan },
  { name: "qr-code", category: "tech", keywords: ["code", "scan", "qr"], node: QrCode },
  { name: "test-tube", category: "tech", keywords: ["experiment", "test"], node: TestTube },
  { name: "shield-check", category: "tech", keywords: ["security", "verified", "geprueft", "sicher"], node: ShieldCheck },
  { name: "fingerprint-pattern", category: "tech", keywords: ["biometrics", "identity", "fingerabdruck"], node: FingerprintPattern },
  { name: "scan-face", category: "tech", keywords: ["biometrics", "gesicht"], node: ScanFace },
  // Communication & people
  { name: "mail", category: "people", keywords: ["email", "envelope", "post", "brief"], node: Mail },
  { name: "message-circle", category: "people", keywords: ["chat", "comment", "nachricht"], node: MessageCircle },
  { name: "message-square", category: "people", keywords: ["chat", "comment", "nachricht"], node: MessageSquare },
  { name: "phone", category: "people", keywords: ["call", "telefon"], node: Phone },
  { name: "user", category: "people", keywords: ["person", "profile", "benutzer"], node: User },
  { name: "users", category: "people", keywords: ["people", "team", "gruppe"], node: Users },
  { name: "contact", category: "people", keywords: ["address-book", "person", "kontakt"], node: Contact },
  { name: "at-sign", category: "people", keywords: ["email", "mention"], node: AtSign },
  { name: "megaphone", category: "people", keywords: ["announcement", "marketing", "megafon"], node: Megaphone },
  { name: "rss", category: "people", keywords: ["feed", "subscribe"], node: Rss },
  { name: "thumbs-up", category: "people", keywords: ["like", "approve", "daumen"], node: ThumbsUp },
  { name: "mails", category: "people", keywords: ["inbox", "emails", "briefe"], node: Mails },
  { name: "mail-open", category: "people", keywords: ["read", "email", "brief", "geoeffnet"], node: MailOpen },
  { name: "mail-plus", category: "people", keywords: ["compose", "neue", "mail"], node: MailPlus },
  { name: "mail-check", category: "people", keywords: ["sent", "email", "mail", "geprueft"], node: MailCheck },
  { name: "send-horizontal", category: "people", keywords: ["submit", "senden"], node: SendHorizontal },
  { name: "reply", category: "people", keywords: ["answer", "antworten"], node: Reply },
  { name: "reply-all", category: "people", keywords: ["answer", "allen", "antworten"], node: ReplyAll },
  { name: "forward", category: "people", keywords: ["share", "weiterleiten"], node: Forward },
  { name: "message-circle-more", category: "people", keywords: ["chat", "conversation", "unterhaltung"], node: MessageCircleMore },
  { name: "messages-square", category: "people", keywords: ["threads", "chat", "unterhaltungen"], node: MessagesSquare },
  { name: "speech", category: "people", keywords: ["talk", "sprechen"], node: Speech },
  { name: "phone-call", category: "people", keywords: ["ringing", "anruf"], node: PhoneCall },
  { name: "user-plus", category: "people", keywords: ["add", "person", "benutzer", "hinzufuegen"], node: UserPlus },
  { name: "user-check", category: "people", keywords: ["verified", "person", "benutzer", "geprueft"], node: UserCheck },
  { name: "user-round", category: "people", keywords: ["person", "profile", "benutzer"], node: UserRound },
  { name: "circle-user-round", category: "people", keywords: ["avatar", "profile", "profil"], node: CircleUserRound },
  { name: "id-card", category: "people", keywords: ["identity", "ausweis"], node: IdCard },
  { name: "book-user", category: "people", keywords: ["address", "book", "adressbuch"], node: BookUser },
  { name: "share-2", category: "people", keywords: ["share", "teilen"], node: Share2 },
  { name: "bell-ring", category: "people", keywords: ["notification", "alarm", "glocke"], node: BellRing },
  { name: "bell-off", category: "people", keywords: ["muted", "stumm", "glocke"], node: BellOff },
  { name: "heart-handshake", category: "people", keywords: ["support", "hilfe", "unterstuetzung"], node: HeartHandshake },
  { name: "hand", category: "people", keywords: ["wave", "stop", "hand"], node: Hand },
  // Creative & media
  { name: "palette", category: "media", keywords: ["color", "art", "design", "farbe"], node: Palette },
  { name: "brush", category: "media", keywords: ["paint", "art", "pinsel"], node: Brush },
  { name: "pen", category: "media", keywords: ["write", "ink", "stift"], node: Pen },
  { name: "pen-tool", category: "media", keywords: ["vector", "design", "kurve"], node: PenTool },
  { name: "pencil", category: "media", keywords: ["write", "draw", "edit", "bleistift"], node: Pencil },
  { name: "camera", category: "media", keywords: ["photo", "picture", "kamera", "foto"], node: Camera },
  { name: "image", category: "media", keywords: ["picture", "photo", "bild"], node: Image },
  { name: "film", category: "media", keywords: ["movie", "cinema", "kino"], node: Film },
  { name: "clapperboard", category: "media", keywords: ["movie", "scene", "film"], node: Clapperboard },
  { name: "video", category: "media", keywords: ["camera", "record", "film"], node: Video },
  { name: "music", category: "media", keywords: ["note", "song", "audio", "musik"], node: Music },
  { name: "mic", category: "media", keywords: ["microphone", "podcast", "mikrofon"], node: Mic },
  { name: "headphones", category: "media", keywords: ["audio", "listen", "kopfhoerer"], node: Headphones },
  { name: "guitar", category: "media", keywords: ["music", "instrument", "gitarre"], node: Guitar },
  { name: "sparkles", category: "media", keywords: ["magic", "stars", "ai", "funkeln"], node: Sparkles },
  { name: "paintbrush", category: "media", keywords: ["paint", "art", "pinsel"], node: Paintbrush },
  { name: "paint-bucket", category: "media", keywords: ["fill", "farbe", "fuellen"], node: PaintBucket },
  { name: "pipette", category: "media", keywords: ["color", "picker", "pipette"], node: Pipette },
  { name: "droplet", category: "media", keywords: ["color", "opacity", "tropfen"], node: Droplet },
  { name: "layers", category: "media", keywords: ["stack", "design", "ebenen"], node: Layers },
  { name: "frame", category: "media", keywords: ["canvas", "artboard", "rahmen"], node: Frame },
  { name: "crop", category: "media", keywords: ["trim", "image", "zuschneiden"], node: Crop },
  { name: "image-plus", category: "media", keywords: ["add", "picture", "bild", "hinzufuegen"], node: ImagePlus },
  { name: "images", category: "media", keywords: ["gallery", "photos", "bilder", "galerie"], node: Images },
  { name: "contrast", category: "media", keywords: ["image", "kontrast"], node: Contrast },
  { name: "wand-sparkles", category: "media", keywords: ["magic", "effects", "zauberstab"], node: WandSparkles },
  { name: "scissors", category: "media", keywords: ["cut", "schere"], node: Scissors },
  { name: "shapes", category: "media", keywords: ["design", "formen"], node: Shapes },
  { name: "volume-2", category: "media", keywords: ["sound", "audio", "lautstaerke"], node: Volume2 },
  { name: "volume-x", category: "media", keywords: ["mute", "stumm"], node: VolumeX },
  { name: "audio-lines", category: "media", keywords: ["waveform", "audio"], node: AudioLines },
  { name: "play", category: "media", keywords: ["start", "abspielen"], node: Play },
  { name: "pause", category: "media", keywords: ["halt", "pause"], node: Pause },
  { name: "circle-play", category: "media", keywords: ["video", "start", "abspielen"], node: CirclePlay },
  { name: "list-music", category: "media", keywords: ["playlist", "musik", "liste"], node: ListMusic },
  { name: "tv", category: "media", keywords: ["television", "fernseher"], node: Tv },
  // Home & everyday life
  { name: "house", category: "life", keywords: ["home", "building", "haus", "zuhause"], node: House },
  { name: "heart", category: "life", keywords: ["love", "favorite", "like", "herz"], node: Heart },
  { name: "star", category: "life", keywords: ["favorite", "rating", "stern"], node: Star },
  { name: "coffee", category: "life", keywords: ["cup", "cafe", "drink", "kaffee"], node: Coffee },
  { name: "utensils", category: "life", keywords: ["food", "eat", "restaurant", "essen", "besteck"], node: Utensils },
  { name: "chef-hat", category: "life", keywords: ["cooking", "kitchen", "recipe", "kochen"], node: ChefHat },
  { name: "pizza", category: "life", keywords: ["food", "italian", "essen"], node: Pizza },
  { name: "cake", category: "life", keywords: ["birthday", "dessert", "kuchen"], node: Cake },
  { name: "apple", category: "life", keywords: ["fruit", "food", "apfel", "obst"], node: Apple },
  { name: "wine", category: "life", keywords: ["glass", "drink", "wein"], node: Wine },
  { name: "baby", category: "life", keywords: ["child", "family", "kind"], node: Baby },
  { name: "shopping-cart", category: "life", keywords: ["buy", "store", "einkaufen"], node: ShoppingCart },
  { name: "gift", category: "life", keywords: ["present", "birthday", "geschenk"], node: Gift },
  { name: "party-popper", category: "life", keywords: ["celebration", "confetti", "feier"], node: PartyPopper },
  { name: "award", category: "life", keywords: ["badge", "ribbon", "auszeichnung"], node: Award },
  { name: "trophy", category: "life", keywords: ["prize", "winner", "pokal"], node: Trophy },
  { name: "crown", category: "life", keywords: ["king", "royal", "krone"], node: Crown },
  { name: "stethoscope", category: "life", keywords: ["doctor", "medical", "health", "arzt"], node: Stethoscope },
  { name: "pill", category: "life", keywords: ["medicine", "drug", "medikament", "tablette"], node: Pill },
  { name: "heart-pulse", category: "life", keywords: ["health", "heartbeat", "gesundheit"], node: HeartPulse },
  { name: "dumbbell", category: "life", keywords: ["gym", "fitness", "workout", "hantel", "sport"], node: Dumbbell },
  { name: "gamepad-2", category: "life", keywords: ["gaming", "controller", "spiel"], node: Gamepad2 },
  { name: "puzzle", category: "life", keywords: ["jigsaw", "plugin", "raetsel"], node: Puzzle },
  { name: "building", category: "life", keywords: ["office", "city", "gebaeude"], node: Building },
  { name: "store", category: "life", keywords: ["shop", "market", "laden"], node: Store },
  { name: "house-plus", category: "life", keywords: ["new", "home", "haus"], node: HousePlus },
  { name: "door-open", category: "life", keywords: ["entrance", "tuer"], node: DoorOpen },
  { name: "armchair", category: "life", keywords: ["furniture", "living", "sessel"], node: Armchair },
  { name: "bed", category: "life", keywords: ["sleep", "bedroom", "bett"], node: Bed },
  { name: "bath", category: "life", keywords: ["bathroom", "bad"], node: Bath },
  { name: "sofa", category: "life", keywords: ["living", "couch", "sofa"], node: Sofa },
  { name: "shirt", category: "life", keywords: ["clothes", "kleidung", "hemd"], node: Shirt },
  { name: "soup", category: "life", keywords: ["food", "meal", "suppe"], node: Soup },
  { name: "salad", category: "life", keywords: ["food", "healthy", "salat"], node: Salad },
  { name: "sandwich", category: "life", keywords: ["food", "lunch", "sandwich"], node: Sandwich },
  { name: "beer", category: "life", keywords: ["drink", "bier"], node: Beer },
  { name: "candy", category: "life", keywords: ["sweets", "suessigkeiten"], node: Candy },
  { name: "ice-cream-cone", category: "life", keywords: ["dessert", "eis"], node: IceCreamCone },
  { name: "carrot", category: "life", keywords: ["vegetable", "gemuese", "moehre"], node: Carrot },
  { name: "cherry", category: "life", keywords: ["fruit", "obst", "kirsche"], node: Cherry },
  { name: "grape", category: "life", keywords: ["fruit", "obst", "traube"], node: Grape },
  { name: "shopping-bag", category: "life", keywords: ["buy", "einkaufstasche"], node: ShoppingBag },
  { name: "shopping-basket", category: "life", keywords: ["groceries", "einkaufskorb"], node: ShoppingBasket },
  { name: "medal", category: "life", keywords: ["award", "medaille"], node: Medal },
  { name: "tickets", category: "life", keywords: ["event", "tickets", "karten"], node: Tickets },
  // Nature & weather
  { name: "sun", category: "nature", keywords: ["weather", "day", "summer", "sonne"], node: Sun },
  { name: "moon", category: "nature", keywords: ["night", "sleep", "dark", "mond"], node: Moon },
  { name: "cloud-rain", category: "nature", keywords: ["weather", "rain", "regen"], node: CloudRain },
  { name: "umbrella", category: "nature", keywords: ["rain", "weather", "regenschirm"], node: Umbrella },
  { name: "tree-pine", category: "nature", keywords: ["tree", "forest", "nature", "baum", "wald"], node: TreePine },
  { name: "leaf", category: "nature", keywords: ["plant", "nature", "eco", "blatt"], node: Leaf },
  { name: "flower", category: "nature", keywords: ["plant", "garden", "blume"], node: Flower },
  { name: "dog", category: "nature", keywords: ["pet", "animal", "hund"], node: Dog },
  { name: "cat", category: "nature", keywords: ["pet", "animal", "katze"], node: Cat },
  { name: "bird", category: "nature", keywords: ["animal", "tweet", "vogel"], node: Bird },
  { name: "fish", category: "nature", keywords: ["animal", "sea", "fisch"], node: Fish },
  { name: "earth", category: "nature", keywords: ["globe", "world", "planet", "erde"], node: Earth },
  { name: "cloud-sun", category: "nature", keywords: ["weather", "wetter", "sonne", "wolke"], node: CloudSun },
  { name: "cloud-moon", category: "nature", keywords: ["weather", "nacht", "wolke"], node: CloudMoon },
  { name: "cloud-snow", category: "nature", keywords: ["weather", "snow", "schnee"], node: CloudSnow },
  { name: "cloud-lightning", category: "nature", keywords: ["weather", "storm", "gewitter"], node: CloudLightning },
  { name: "snowflake", category: "nature", keywords: ["winter", "cold", "schneeflocke"], node: Snowflake },
  { name: "wind", category: "nature", keywords: ["weather", "wind"], node: Wind },
  { name: "tornado", category: "nature", keywords: ["storm", "sturm"], node: Tornado },
  { name: "rainbow", category: "nature", keywords: ["weather", "regenbogen"], node: Rainbow },
  { name: "thermometer", category: "nature", keywords: ["temperature", "thermometer"], node: Thermometer },
  { name: "droplets", category: "nature", keywords: ["water", "humidity", "wasser"], node: Droplets },
  { name: "sunrise", category: "nature", keywords: ["morning", "sonnenaufgang"], node: Sunrise },
  { name: "sunset", category: "nature", keywords: ["evening", "sonnenuntergang"], node: Sunset },
  { name: "sprout", category: "nature", keywords: ["plant", "growth", "pflanze"], node: Sprout },
  { name: "trees", category: "nature", keywords: ["forest", "wald", "baeume"], node: Trees },
  { name: "tree-deciduous", category: "nature", keywords: ["tree", "laubbaum"], node: TreeDeciduous },
  { name: "tree-palm", category: "nature", keywords: ["tropical", "palme"], node: TreePalm },
  { name: "rabbit", category: "nature", keywords: ["animal", "hase"], node: Rabbit },
  { name: "squirrel", category: "nature", keywords: ["animal", "eichhoernchen"], node: Squirrel },
  { name: "turtle", category: "nature", keywords: ["animal", "schildkroete"], node: Turtle },
  { name: "paw-print", category: "nature", keywords: ["pet", "animal", "pfote"], node: PawPrint },
  { name: "feather", category: "nature", keywords: ["bird", "light", "feder"], node: Feather },
  { name: "mountain-snow", category: "nature", keywords: ["alps", "berg", "schnee"], node: MountainSnow },
  { name: "telescope", category: "nature", keywords: ["astronomy", "teleskop"], node: Telescope },
  { name: "atom", category: "nature", keywords: ["physics", "science", "atom"], node: Atom },
  { name: "recycle", category: "nature", keywords: ["eco", "recycling"], node: Recycle },
  // Travel & places
  { name: "car", category: "travel", keywords: ["vehicle", "drive", "auto"], node: Car },
  { name: "bike", category: "travel", keywords: ["bicycle", "cycling", "fahrrad"], node: Bike },
  { name: "plane", category: "travel", keywords: ["airplane", "travel", "flight", "flugzeug", "reise"], node: Plane },
  { name: "train-front", category: "travel", keywords: ["railway", "travel", "zug", "bahn"], node: TrainFront },
  { name: "ship", category: "travel", keywords: ["boat", "cruise", "schiff"], node: Ship },
  { name: "map", category: "travel", keywords: ["travel", "location", "karte"], node: MapIcon },
  { name: "map-pin", category: "travel", keywords: ["location", "place", "marker", "ort"], node: MapPin },
  { name: "compass", category: "travel", keywords: ["navigation", "direction", "kompass"], node: Compass },
  { name: "mountain", category: "travel", keywords: ["hiking", "outdoor", "berg"], node: Mountain },
  { name: "tent", category: "travel", keywords: ["camping", "outdoor", "zelt"], node: Tent },
  { name: "map-pinned", category: "travel", keywords: ["location", "saved", "ort", "gemerkt"], node: MapPinned },
  { name: "navigation", category: "travel", keywords: ["direction", "navigation"], node: Navigation },
  { name: "locate-fixed", category: "travel", keywords: ["gps", "position", "standort"], node: LocateFixed },
  { name: "signpost", category: "travel", keywords: ["direction", "wegweiser"], node: Signpost },
  { name: "car-front", category: "travel", keywords: ["drive", "auto"], node: CarFront },
  { name: "bus", category: "travel", keywords: ["transport", "bus"], node: Bus },
  { name: "tram-front", category: "travel", keywords: ["transport", "strassenbahn"], node: TramFront },
  { name: "plane-takeoff", category: "travel", keywords: ["departure", "abflug"], node: PlaneTakeoff },
  { name: "plane-landing", category: "travel", keywords: ["arrival", "ankunft"], node: PlaneLanding },
  { name: "luggage", category: "travel", keywords: ["suitcase", "gepaeck"], node: Luggage },
  { name: "backpack", category: "travel", keywords: ["hiking", "rucksack"], node: Backpack },
  { name: "sailboat", category: "travel", keywords: ["boat", "segelboot"], node: Sailboat },
  { name: "anchor", category: "travel", keywords: ["harbour", "anker"], node: Anchor },
  { name: "fuel", category: "travel", keywords: ["gas", "station", "tankstelle"], node: Fuel },
  { name: "hotel", category: "travel", keywords: ["accommodation", "hotel"], node: Hotel },
  { name: "castle", category: "travel", keywords: ["historic", "burg", "schloss"], node: Castle },
  { name: "ferris-wheel", category: "travel", keywords: ["fair", "riesenrad"], node: FerrisWheel },
  // Money & numbers
  { name: "wallet", category: "finance", keywords: ["money", "finance", "geldboerse"], node: Wallet },
  { name: "credit-card", category: "finance", keywords: ["payment", "money", "kreditkarte"], node: CreditCard },
  { name: "banknote", category: "finance", keywords: ["money", "cash", "dollar", "geld", "geldschein"], node: Banknote },
  { name: "dollar-sign", category: "finance", keywords: ["money", "currency", "usd"], node: DollarSign },
  { name: "euro", category: "finance", keywords: ["money", "currency", "geld"], node: Euro },
  { name: "coins", category: "finance", keywords: ["money", "change", "muenzen"], node: Coins },
  { name: "piggy-bank", category: "finance", keywords: ["savings", "money", "sparschwein"], node: PiggyBank },
  { name: "chart-column", category: "finance", keywords: ["bar-chart", "statistics", "diagramm", "statistik"], node: ChartColumn },
  { name: "chart-line", category: "finance", keywords: ["line-chart", "graph", "diagramm"], node: ChartLine },
  { name: "chart-pie", category: "finance", keywords: ["pie-chart", "statistics", "diagramm"], node: ChartPie },
  { name: "trending-up", category: "finance", keywords: ["growth", "increase", "wachstum"], node: TrendingUp },
  { name: "calculator", category: "finance", keywords: ["math", "numbers", "taschenrechner"], node: Calculator },
  { name: "landmark", category: "finance", keywords: ["bank", "government", "museum"], node: Landmark },
  { name: "banknote-arrow-up", category: "finance", keywords: ["income", "einnahme"], node: BanknoteArrowUp },
  { name: "banknote-arrow-down", category: "finance", keywords: ["expense", "ausgabe"], node: BanknoteArrowDown },
  { name: "hand-coins", category: "finance", keywords: ["payment", "zahlung"], node: HandCoins },
  { name: "badge-euro", category: "finance", keywords: ["price", "preis", "euro"], node: BadgeEuro },
  { name: "badge-dollar-sign", category: "finance", keywords: ["price", "preis"], node: BadgeDollarSign },
  { name: "circle-dollar-sign", category: "finance", keywords: ["money", "geld"], node: CircleDollarSign },
  { name: "bitcoin", category: "finance", keywords: ["crypto", "currency"], node: Bitcoin },
  { name: "receipt-text", category: "finance", keywords: ["invoice", "bill", "rechnung"], node: ReceiptText },
  { name: "file-chart-column", category: "finance", keywords: ["report", "bericht"], node: FileChartColumn },
  { name: "chart-bar", category: "finance", keywords: ["statistics", "diagramm"], node: ChartBar },
  { name: "chart-area", category: "finance", keywords: ["trend", "diagramm"], node: ChartArea },
  { name: "chart-scatter", category: "finance", keywords: ["data", "diagramm"], node: ChartScatter },
  { name: "trending-down", category: "finance", keywords: ["decline", "rueckgang"], node: TrendingDown },
  { name: "percent", category: "finance", keywords: ["rate", "prozent"], node: Percent },
  { name: "vault", category: "finance", keywords: ["safe", "tresor"], node: Vault },
  // Symbols & states
  { name: "lightbulb", category: "symbols", keywords: ["idea", "tip", "idee", "gluehbirne"], node: Lightbulb },
  { name: "rocket", category: "symbols", keywords: ["launch", "startup", "space", "rakete"], node: Rocket },
  { name: "bell", category: "symbols", keywords: ["notification", "alarm", "glocke"], node: Bell },
  { name: "lock", category: "symbols", keywords: ["secure", "private", "schloss"], node: Lock },
  { name: "key", category: "symbols", keywords: ["password", "access", "schluessel"], node: Key },
  { name: "shield", category: "symbols", keywords: ["security", "protection", "schutz"], node: Shield },
  { name: "settings", category: "symbols", keywords: ["gear", "preferences", "einstellungen"], node: Settings },
  { name: "wrench", category: "symbols", keywords: ["tool", "fix", "werkzeug"], node: Wrench },
  { name: "hammer", category: "symbols", keywords: ["tool", "build", "werkzeug"], node: Hammer },
  { name: "trash-2", category: "symbols", keywords: ["trash", "delete", "bin", "papierkorb"], node: Trash2 },
  { name: "triangle-alert", category: "symbols", keywords: ["alert-triangle", "warning", "caution", "warnung"], node: TriangleAlert },
  { name: "info", category: "symbols", keywords: ["information", "about", "hinweis"], node: Info },
  { name: "circle-question-mark", category: "symbols", keywords: ["help-circle", "help", "question", "faq", "hilfe", "frage"], node: CircleQuestionMark },
  { name: "smile", category: "symbols", keywords: ["happy", "emoji", "face", "laecheln"], node: Smile },
  { name: "ghost", category: "symbols", keywords: ["spooky", "halloween", "geist"], node: Ghost },
  { name: "zap", category: "symbols", keywords: ["lightning", "energy", "flash", "blitz"], node: Zap },
  { name: "flame", category: "symbols", keywords: ["fire", "hot", "streak", "feuer"], node: Flame },
  { name: "eye", category: "symbols", keywords: ["view", "watch", "auge"], node: Eye },
  { name: "circle-alert", category: "symbols", keywords: ["warning", "error", "warnung"], node: CircleAlert },
  { name: "octagon-alert", category: "symbols", keywords: ["danger", "stop", "gefahr"], node: OctagonAlert },
  { name: "circle-x", category: "symbols", keywords: ["error", "close", "fehler"], node: CircleX },
  { name: "circle-plus", category: "symbols", keywords: ["add", "hinzufuegen"], node: CirclePlus },
  { name: "circle-minus", category: "symbols", keywords: ["remove", "entfernen"], node: CircleMinus },
  { name: "badge-check", category: "symbols", keywords: ["verified", "geprueft"], node: BadgeCheck },
  { name: "badge-alert", category: "symbols", keywords: ["attention", "achtung"], node: BadgeAlert },
  { name: "badge-info", category: "symbols", keywords: ["note", "hinweis"], node: BadgeInfo },
  { name: "asterisk", category: "symbols", keywords: ["footnote", "sternchen"], node: Asterisk },
  { name: "arrow-right", category: "symbols", keywords: ["next", "weiter", "pfeil"], node: ArrowRight },
  { name: "refresh-cw", category: "symbols", keywords: ["reload", "aktualisieren"], node: RefreshCw },
  { name: "rotate-ccw", category: "symbols", keywords: ["undo", "zurueck"], node: RotateCcw },
  { name: "history", category: "symbols", keywords: ["versions", "verlauf"], node: History },
  { name: "archive-restore", category: "symbols", keywords: ["restore", "wiederherstellen"], node: ArchiveRestore },
  { name: "lock-open", category: "symbols", keywords: ["unlocked", "entsperrt"], node: LockOpen },
  { name: "shield-alert", category: "symbols", keywords: ["risk", "warnung", "schutz"], node: ShieldAlert },
  { name: "shield-off", category: "symbols", keywords: ["unprotected", "ungeschuetzt"], node: ShieldOff },
  { name: "eye-off", category: "symbols", keywords: ["hidden", "verborgen"], node: EyeOff },
  { name: "funnel", category: "symbols", keywords: ["filter", "trichter"], node: Funnel },
  { name: "sliders-horizontal", category: "symbols", keywords: ["settings", "regler"], node: SlidersHorizontal },
  { name: "toggle-right", category: "symbols", keywords: ["switch", "on", "schalter"], node: ToggleRight },
  { name: "grip", category: "symbols", keywords: ["drag", "handle", "griff"], node: Grip },
  { name: "maximize-2", category: "symbols", keywords: ["expand", "vergroessern"], node: Maximize2 },
  { name: "minimize-2", category: "symbols", keywords: ["collapse", "verkleinern"], node: Minimize2 },
  { name: "external-link", category: "symbols", keywords: ["open", "extern", "oeffnen"], node: ExternalLink },
  { name: "copy", category: "symbols", keywords: ["duplicate", "kopieren"], node: Copy },
  { name: "clipboard-check", category: "symbols", keywords: ["pasted", "eingefuegt"], node: ClipboardCheck },
  { name: "circle", category: "symbols", keywords: ["shape", "kreis"], node: Circle },
  { name: "triangle", category: "symbols", keywords: ["shape", "dreieck"], node: Triangle },
  { name: "diamond", category: "symbols", keywords: ["shape", "raute"], node: Diamond },
  { name: "hexagon", category: "symbols", keywords: ["shape", "sechseck"], node: Hexagon },
  { name: "infinity", category: "symbols", keywords: ["endless", "unendlich"], node: InfinityIcon },
];

/** Entries of one category, in catalogue order (the picker's tabs). */
export function lucideIconsByCategory(category: LucideIconCategory): LucideIconEntry[] {
  return LUCIDE_ICONS.filter((entry) => entry.category === category);
}

export const LUCIDE_ICON_MAP: Map<string, LucideIconEntry> = new Map(
  LUCIDE_ICONS.map((entry) => [entry.name, entry]),
);

// The catalogue grew from 165 to 400 (E2), so a broad query like "a" would match
// half of it. The cap keeps the result grid a glance rather than a wall; the
// category tabs are the way to BROWSE, search is the way to aim.
const MAX_SEARCH_RESULTS = 120;

export function searchLucideIcons(query: string): LucideIconEntry[] {
  const q = query.trim().toLowerCase();
  if (q === "") return LUCIDE_ICONS;
  // Name hits rank before keyword-only hits; one pass per entry keeps results deduped.
  const nameMatches: LucideIconEntry[] = [];
  const keywordMatches: LucideIconEntry[] = [];
  for (const entry of LUCIDE_ICONS) {
    if (entry.name.includes(q)) {
      nameMatches.push(entry);
    } else if (entry.keywords?.some((keyword) => keyword.toLowerCase().includes(q))) {
      keywordMatches.push(entry);
    }
  }
  return [...nameMatches, ...keywordMatches].slice(0, MAX_SEARCH_RESULTS);
}
