import type { IconNode } from "lucide";
import {
  Apple,
  Archive,
  AtSign,
  Award,
  Baby,
  Banknote,
  Bell,
  Bike,
  Bird,
  Book,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building,
  Cake,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  Cat,
  ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  ChefHat,
  CircleCheck,
  CircleQuestionMark,
  Clapperboard,
  Clipboard,
  ClipboardList,
  Clock,
  Cloud,
  CloudRain,
  Code,
  Coffee,
  Coins,
  Compass,
  Contact,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Dna,
  Dog,
  DollarSign,
  Dumbbell,
  Earth,
  Euro,
  Eye,
  File,
  FileText,
  Files,
  Film,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower,
  Folder,
  FolderOpen,
  FolderTree,
  Gamepad2,
  Ghost,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  HardDrive,
  Headphones,
  Heart,
  HeartPulse,
  House,
  Image,
  Inbox,
  Info,
  Kanban,
  Key,
  Keyboard,
  Landmark,
  Laptop,
  LayoutDashboard,
  Leaf,
  Library,
  Lightbulb,
  Link,
  List,
  ListTodo,
  Lock,
  Mail,
  // Renamed so `new Map()` below keeps referring to the global Map constructor.
  Map as MapIcon,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Newspaper,
  Notebook,
  NotebookPen,
  Package,
  Palette,
  Paperclip,
  PartyPopper,
  Pen,
  PenTool,
  Pencil,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Presentation,
  Puzzle,
  Rocket,
  Rss,
  School,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  Ship,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  StickyNote,
  Store,
  Sun,
  Table,
  Tag,
  Target,
  Tent,
  Terminal,
  ThumbsUp,
  Timer,
  TrainFront,
  Trash2,
  TreePine,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Umbrella,
  User,
  Users,
  Utensils,
  Video,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from "lucide";

export interface LucideIconEntry {
  name: string;
  keywords?: string[];
  node: IconNode;
}

// `name` is the official lucide kebab-case id. It is persisted in user files as
// `lucide:<name>`, so entries must keep the exact upstream naming.
export const LUCIDE_ICONS: LucideIconEntry[] = [
  // Knowledge & files
  { name: "book", keywords: ["knowledge", "reading", "buch"], node: Book },
  { name: "book-open", keywords: ["reading", "study", "buch"], node: BookOpen },
  { name: "notebook", keywords: ["journal", "notes", "notizbuch"], node: Notebook },
  { name: "notebook-pen", keywords: ["journal", "writing", "notizen"], node: NotebookPen },
  { name: "library", keywords: ["books", "collection", "bibliothek"], node: Library },
  { name: "folder", keywords: ["directory", "ordner"], node: Folder },
  { name: "folder-open", keywords: ["directory", "ordner"], node: FolderOpen },
  { name: "folder-tree", keywords: ["structure", "hierarchy", "ordner"], node: FolderTree },
  { name: "file", keywords: ["document", "datei"], node: File },
  { name: "file-text", keywords: ["document", "note", "datei"], node: FileText },
  { name: "files", keywords: ["documents", "copies", "dateien"], node: Files },
  { name: "archive", keywords: ["box", "storage", "archiv"], node: Archive },
  { name: "newspaper", keywords: ["news", "press", "zeitung"], node: Newspaper },
  { name: "sticky-note", keywords: ["memo", "post-it", "notiz"], node: StickyNote },
  { name: "clipboard", keywords: ["paste", "zwischenablage"], node: Clipboard },
  { name: "clipboard-list", keywords: ["tasks", "checklist", "liste"], node: ClipboardList },
  // Work & productivity
  { name: "briefcase", keywords: ["work", "business", "job", "arbeit"], node: Briefcase },
  { name: "calendar", keywords: ["date", "schedule", "kalender"], node: Calendar },
  { name: "calendar-days", keywords: ["date", "month", "kalender"], node: CalendarDays },
  { name: "clock", keywords: ["time", "watch", "uhr"], node: Clock },
  { name: "timer", keywords: ["stopwatch", "countdown", "zeit"], node: Timer },
  { name: "target", keywords: ["goal", "aim", "ziel"], node: Target },
  { name: "flag", keywords: ["milestone", "marker", "flagge"], node: Flag },
  { name: "check", keywords: ["done", "tick", "erledigt"], node: Check },
  { name: "circle-check", keywords: ["done", "complete", "erledigt"], node: CircleCheck },
  { name: "list", keywords: ["items", "bullets", "liste"], node: List },
  { name: "list-todo", keywords: ["tasks", "checklist", "aufgaben"], node: ListTodo },
  { name: "kanban", keywords: ["board", "columns", "projekt"], node: Kanban },
  { name: "layout-dashboard", keywords: ["overview", "panels", "uebersicht"], node: LayoutDashboard },
  { name: "table", keywords: ["grid", "spreadsheet", "tabelle"], node: Table },
  { name: "presentation", keywords: ["slides", "meeting", "praesentation"], node: Presentation },
  { name: "inbox", keywords: ["tray", "incoming", "eingang"], node: Inbox },
  { name: "send", keywords: ["paper-plane", "submit", "senden"], node: Send },
  // Tech
  { name: "code", keywords: ["programming", "developer", "quellcode"], node: Code },
  { name: "terminal", keywords: ["console", "shell", "command"], node: Terminal },
  { name: "cpu", keywords: ["chip", "processor", "prozessor"], node: Cpu },
  { name: "database", keywords: ["storage", "sql", "datenbank"], node: Database },
  { name: "server", keywords: ["host", "backend"], node: Server },
  { name: "hard-drive", keywords: ["disk", "storage", "festplatte"], node: HardDrive },
  { name: "monitor", keywords: ["screen", "display", "bildschirm"], node: Monitor },
  { name: "laptop", keywords: ["computer", "notebook"], node: Laptop },
  { name: "smartphone", keywords: ["phone", "mobile", "handy"], node: Smartphone },
  { name: "keyboard", keywords: ["typing", "keys", "tastatur"], node: Keyboard },
  { name: "globe", keywords: ["world", "internet", "web", "welt"], node: Globe },
  { name: "cloud", keywords: ["weather", "hosting", "wolke"], node: Cloud },
  { name: "wifi", keywords: ["wireless", "network", "wlan"], node: Wifi },
  { name: "bug", keywords: ["insect", "debug", "fehler", "kaefer"], node: Bug },
  { name: "bot", keywords: ["robot", "ai", "roboter"], node: Bot },
  { name: "git-branch", keywords: ["version", "fork", "zweig"], node: GitBranch },
  // Communication & people
  { name: "mail", keywords: ["email", "envelope", "post", "brief"], node: Mail },
  { name: "message-circle", keywords: ["chat", "comment", "nachricht"], node: MessageCircle },
  { name: "message-square", keywords: ["chat", "comment", "nachricht"], node: MessageSquare },
  { name: "phone", keywords: ["call", "telefon"], node: Phone },
  { name: "user", keywords: ["person", "profile", "benutzer"], node: User },
  { name: "users", keywords: ["people", "team", "gruppe"], node: Users },
  { name: "contact", keywords: ["address-book", "person", "kontakt"], node: Contact },
  { name: "at-sign", keywords: ["email", "mention"], node: AtSign },
  { name: "megaphone", keywords: ["announcement", "marketing", "megafon"], node: Megaphone },
  { name: "rss", keywords: ["feed", "subscribe"], node: Rss },
  // Creative & media
  { name: "palette", keywords: ["color", "art", "design", "farbe"], node: Palette },
  { name: "brush", keywords: ["paint", "art", "pinsel"], node: Brush },
  { name: "pen", keywords: ["write", "ink", "stift"], node: Pen },
  { name: "pen-tool", keywords: ["vector", "design", "kurve"], node: PenTool },
  { name: "pencil", keywords: ["write", "draw", "edit", "bleistift"], node: Pencil },
  { name: "camera", keywords: ["photo", "picture", "kamera", "foto"], node: Camera },
  { name: "image", keywords: ["picture", "photo", "bild"], node: Image },
  { name: "film", keywords: ["movie", "cinema", "kino"], node: Film },
  { name: "clapperboard", keywords: ["movie", "scene", "film"], node: Clapperboard },
  { name: "video", keywords: ["camera", "record", "film"], node: Video },
  { name: "music", keywords: ["note", "song", "audio", "musik"], node: Music },
  { name: "mic", keywords: ["microphone", "podcast", "mikrofon"], node: Mic },
  { name: "headphones", keywords: ["audio", "listen", "kopfhoerer"], node: Headphones },
  { name: "guitar", keywords: ["music", "instrument", "gitarre"], node: Guitar },
  { name: "sparkles", keywords: ["magic", "stars", "ai", "funkeln"], node: Sparkles },
  // Home & life
  { name: "house", keywords: ["home", "building", "haus", "zuhause"], node: House },
  { name: "heart", keywords: ["love", "favorite", "like", "herz"], node: Heart },
  { name: "star", keywords: ["favorite", "rating", "stern"], node: Star },
  { name: "coffee", keywords: ["cup", "cafe", "drink", "kaffee"], node: Coffee },
  { name: "utensils", keywords: ["food", "eat", "restaurant", "essen", "besteck"], node: Utensils },
  { name: "chef-hat", keywords: ["cooking", "kitchen", "recipe", "kochen"], node: ChefHat },
  { name: "pizza", keywords: ["food", "italian", "essen"], node: Pizza },
  { name: "cake", keywords: ["birthday", "dessert", "kuchen"], node: Cake },
  { name: "apple", keywords: ["fruit", "food", "apfel", "obst"], node: Apple },
  { name: "wine", keywords: ["glass", "drink", "wein"], node: Wine },
  { name: "car", keywords: ["vehicle", "drive", "auto"], node: Car },
  { name: "bike", keywords: ["bicycle", "cycling", "fahrrad"], node: Bike },
  { name: "plane", keywords: ["airplane", "travel", "flight", "flugzeug", "reise"], node: Plane },
  { name: "train-front", keywords: ["railway", "travel", "zug", "bahn"], node: TrainFront },
  { name: "ship", keywords: ["boat", "cruise", "schiff"], node: Ship },
  { name: "map", keywords: ["travel", "location", "karte"], node: MapIcon },
  { name: "map-pin", keywords: ["location", "place", "marker", "ort"], node: MapPin },
  { name: "compass", keywords: ["navigation", "direction", "kompass"], node: Compass },
  { name: "mountain", keywords: ["hiking", "outdoor", "berg"], node: Mountain },
  { name: "tent", keywords: ["camping", "outdoor", "zelt"], node: Tent },
  { name: "sun", keywords: ["weather", "day", "summer", "sonne"], node: Sun },
  { name: "moon", keywords: ["night", "sleep", "dark", "mond"], node: Moon },
  { name: "cloud-rain", keywords: ["weather", "rain", "regen"], node: CloudRain },
  { name: "umbrella", keywords: ["rain", "weather", "regenschirm"], node: Umbrella },
  { name: "tree-pine", keywords: ["tree", "forest", "nature", "baum", "wald"], node: TreePine },
  { name: "leaf", keywords: ["plant", "nature", "eco", "blatt"], node: Leaf },
  { name: "flower", keywords: ["plant", "garden", "blume"], node: Flower },
  { name: "dog", keywords: ["pet", "animal", "hund"], node: Dog },
  { name: "cat", keywords: ["pet", "animal", "katze"], node: Cat },
  { name: "bird", keywords: ["animal", "tweet", "vogel"], node: Bird },
  { name: "fish", keywords: ["animal", "sea", "fisch"], node: Fish },
  { name: "baby", keywords: ["child", "family", "kind"], node: Baby },
  { name: "shopping-cart", keywords: ["buy", "store", "einkaufen"], node: ShoppingCart },
  // Finance
  { name: "wallet", keywords: ["money", "finance", "geldboerse"], node: Wallet },
  { name: "credit-card", keywords: ["payment", "money", "kreditkarte"], node: CreditCard },
  { name: "banknote", keywords: ["money", "cash", "dollar", "geld", "geldschein"], node: Banknote },
  { name: "dollar-sign", keywords: ["money", "currency", "usd"], node: DollarSign },
  { name: "euro", keywords: ["money", "currency", "geld"], node: Euro },
  { name: "coins", keywords: ["money", "change", "muenzen"], node: Coins },
  { name: "piggy-bank", keywords: ["savings", "money", "sparschwein"], node: PiggyBank },
  { name: "chart-column", keywords: ["bar-chart", "statistics", "diagramm", "statistik"], node: ChartColumn },
  { name: "chart-line", keywords: ["line-chart", "graph", "diagramm"], node: ChartLine },
  { name: "chart-pie", keywords: ["pie-chart", "statistics", "diagramm"], node: ChartPie },
  { name: "trending-up", keywords: ["growth", "increase", "wachstum"], node: TrendingUp },
  { name: "calculator", keywords: ["math", "numbers", "taschenrechner"], node: Calculator },
  { name: "landmark", keywords: ["bank", "government", "museum"], node: Landmark },
  // Misc
  { name: "lightbulb", keywords: ["idea", "tip", "idee", "gluehbirne"], node: Lightbulb },
  { name: "rocket", keywords: ["launch", "startup", "space", "rakete"], node: Rocket },
  { name: "gift", keywords: ["present", "birthday", "geschenk"], node: Gift },
  { name: "party-popper", keywords: ["celebration", "confetti", "feier"], node: PartyPopper },
  { name: "bell", keywords: ["notification", "alarm", "glocke"], node: Bell },
  { name: "lock", keywords: ["secure", "private", "schloss"], node: Lock },
  { name: "key", keywords: ["password", "access", "schluessel"], node: Key },
  { name: "shield", keywords: ["security", "protection", "schutz"], node: Shield },
  { name: "settings", keywords: ["gear", "preferences", "einstellungen"], node: Settings },
  { name: "wrench", keywords: ["tool", "fix", "werkzeug"], node: Wrench },
  { name: "hammer", keywords: ["tool", "build", "werkzeug"], node: Hammer },
  { name: "search", keywords: ["find", "magnifier", "suche"], node: Search },
  { name: "bookmark", keywords: ["save", "favorite", "lesezeichen"], node: Bookmark },
  { name: "tag", keywords: ["label", "category", "etikett"], node: Tag },
  { name: "link", keywords: ["url", "chain", "verknuepfung"], node: Link },
  { name: "paperclip", keywords: ["attachment", "anhang", "bueroklammer"], node: Paperclip },
  { name: "trash-2", keywords: ["trash", "delete", "bin", "papierkorb"], node: Trash2 },
  { name: "triangle-alert", keywords: ["alert-triangle", "warning", "caution", "warnung"], node: TriangleAlert },
  { name: "info", keywords: ["information", "about", "hinweis"], node: Info },
  { name: "circle-question-mark", keywords: ["help-circle", "help", "question", "faq", "hilfe", "frage"], node: CircleQuestionMark },
  { name: "smile", keywords: ["happy", "emoji", "face", "laecheln"], node: Smile },
  { name: "ghost", keywords: ["spooky", "halloween", "geist"], node: Ghost },
  { name: "zap", keywords: ["lightning", "energy", "flash", "blitz"], node: Zap },
  { name: "flame", keywords: ["fire", "hot", "streak", "feuer"], node: Flame },
  { name: "award", keywords: ["badge", "ribbon", "auszeichnung"], node: Award },
  { name: "trophy", keywords: ["prize", "winner", "pokal"], node: Trophy },
  { name: "crown", keywords: ["king", "royal", "krone"], node: Crown },
  { name: "graduation-cap", keywords: ["education", "university", "studium", "abschluss"], node: GraduationCap },
  { name: "stethoscope", keywords: ["doctor", "medical", "health", "arzt"], node: Stethoscope },
  { name: "pill", keywords: ["medicine", "drug", "medikament", "tablette"], node: Pill },
  { name: "heart-pulse", keywords: ["health", "heartbeat", "gesundheit"], node: HeartPulse },
  { name: "dumbbell", keywords: ["gym", "fitness", "workout", "hantel", "sport"], node: Dumbbell },
  { name: "gamepad-2", keywords: ["gaming", "controller", "spiel"], node: Gamepad2 },
  { name: "puzzle", keywords: ["jigsaw", "plugin", "raetsel"], node: Puzzle },
  { name: "eye", keywords: ["view", "watch", "auge"], node: Eye },
  { name: "thumbs-up", keywords: ["like", "approve", "daumen"], node: ThumbsUp },
  { name: "brain", keywords: ["mind", "think", "gehirn"], node: Brain },
  { name: "earth", keywords: ["globe", "world", "planet", "erde"], node: Earth },
  { name: "box", keywords: ["package", "container", "kiste"], node: Box },
  { name: "package", keywords: ["box", "delivery", "paket"], node: Package },
  { name: "building", keywords: ["office", "city", "gebaeude"], node: Building },
  { name: "store", keywords: ["shop", "market", "laden"], node: Store },
  { name: "school", keywords: ["education", "learning", "schule"], node: School },
  { name: "flask-conical", keywords: ["chemistry", "lab", "science", "chemie", "labor"], node: FlaskConical },
  { name: "dna", keywords: ["genetics", "biology", "gene"], node: Dna },
];

export const LUCIDE_ICON_MAP: Map<string, LucideIconEntry> = new Map(
  LUCIDE_ICONS.map((entry) => [entry.name, entry]),
);

const MAX_SEARCH_RESULTS = 60;

export function searchLucideIcons(query: string): LucideIconEntry[] {
  const q = query.trim().toLowerCase();
  if (q === "") return LUCIDE_ICONS;
  // Name hits rank before keyword-only hits; one pass per entry keeps results deduped.
  const nameMatches: LucideIconEntry[] = [];
  const keywordMatches: LucideIconEntry[] = [];
  for (const entry of LUCIDE_ICONS) {
    if (entry.name.includes(q)) {
      nameMatches.push(entry);
    } else if (entry.keywords?.some((keyword) => keyword.toLowerCase().includes(q))) {
      keywordMatches.push(entry);
    }
  }
  return [...nameMatches, ...keywordMatches].slice(0, MAX_SEARCH_RESULTS);
}
