// Curated emoji catalog for the emoji picker. Limited to widely supported
// characters (Unicode <= 15.0, no fragile ZWJ sequences) so they render
// correctly with the system emoji fonts on Windows, macOS and Linux.

export interface EmojiEntry {
  char: string;
  name: string;
  keywords?: string[];
}

export type EmojiCategoryId =
  | "smileys"
  | "people"
  | "animals"
  | "food"
  | "activities"
  | "travel"
  | "objects"
  | "symbols";

export const EMOJI_CATEGORIES: { id: EmojiCategoryId; emoji: EmojiEntry[] }[] = [
  {
    id: "smileys",
    emoji: [
      { char: "😀", name: "grinning face", keywords: ["smile", "happy"] },
      { char: "😃", name: "grinning face with big eyes", keywords: ["smile", "happy"] },
      { char: "😄", name: "grinning face with smiling eyes", keywords: ["laugh", "happy"] },
      { char: "😁", name: "beaming face with smiling eyes", keywords: ["grin"] },
      { char: "😆", name: "grinning squinting face", keywords: ["laugh", "haha"] },
      { char: "😅", name: "grinning face with sweat", keywords: ["relief", "phew"] },
      { char: "🤣", name: "rolling on the floor laughing", keywords: ["rofl", "lol"] },
      { char: "😂", name: "face with tears of joy", keywords: ["lol", "funny", "laugh"] },
      { char: "🙂", name: "slightly smiling face", keywords: ["smile"] },
      { char: "😉", name: "winking face", keywords: ["wink"] },
      { char: "😊", name: "smiling face with smiling eyes", keywords: ["blush", "happy"] },
      { char: "😇", name: "smiling face with halo", keywords: ["angel", "innocent"] },
      { char: "🥰", name: "smiling face with hearts", keywords: ["love", "adore"] },
      { char: "😍", name: "smiling face with heart-eyes", keywords: ["love", "crush"] },
      { char: "🤩", name: "star-struck", keywords: ["excited", "wow"] },
      { char: "😘", name: "face blowing a kiss", keywords: ["kiss", "love"] },
      { char: "😋", name: "face savoring food", keywords: ["yum", "tasty"] },
      { char: "😜", name: "winking face with tongue", keywords: ["joke", "tongue"] },
      { char: "🤪", name: "zany face", keywords: ["goofy", "crazy"] },
      { char: "🤔", name: "thinking face", keywords: ["think", "hmm", "consider"] },
      { char: "🤨", name: "face with raised eyebrow", keywords: ["skeptical", "doubt"] },
      { char: "😐", name: "neutral face", keywords: ["meh"] },
      { char: "😑", name: "expressionless face", keywords: ["blank"] },
      { char: "🙄", name: "face with rolling eyes", keywords: ["eyeroll", "whatever"] },
      { char: "😏", name: "smirking face", keywords: ["smirk", "smug"] },
      { char: "😴", name: "sleeping face", keywords: ["sleep", "zzz", "tired"] },
      { char: "😷", name: "face with medical mask", keywords: ["sick", "mask", "ill"] },
      { char: "🤒", name: "face with thermometer", keywords: ["sick", "fever"] },
      { char: "🤢", name: "nauseated face", keywords: ["sick", "gross"] },
      { char: "🤮", name: "face vomiting", keywords: ["sick", "puke"] },
      { char: "🥵", name: "hot face", keywords: ["heat", "sweating"] },
      { char: "🥶", name: "cold face", keywords: ["freezing", "cold"] },
      { char: "🤯", name: "exploding head", keywords: ["mind blown", "shocked"] },
      { char: "🥳", name: "partying face", keywords: ["party", "celebration", "birthday"] },
      { char: "😎", name: "smiling face with sunglasses", keywords: ["cool"] },
      { char: "🤓", name: "nerd face", keywords: ["geek", "glasses"] },
      { char: "🧐", name: "face with monocle", keywords: ["inspect", "curious"] },
      { char: "😕", name: "confused face", keywords: ["confused"] },
      { char: "😟", name: "worried face", keywords: ["worried", "anxious"] },
      { char: "😮", name: "face with open mouth", keywords: ["wow", "surprised"] },
      { char: "😳", name: "flushed face", keywords: ["embarrassed", "blushing"] },
      { char: "🥺", name: "pleading face", keywords: ["puppy eyes", "please"] },
      { char: "😢", name: "crying face", keywords: ["sad", "tear"] },
      { char: "😭", name: "loudly crying face", keywords: ["sob", "cry"] },
      { char: "😤", name: "face with steam from nose", keywords: ["frustrated", "triumph"] },
      { char: "😠", name: "angry face", keywords: ["angry", "mad"] },
      { char: "😡", name: "pouting face", keywords: ["rage", "furious"] },
      { char: "🤬", name: "face with symbols on mouth", keywords: ["swearing", "cursing"] },
      { char: "😈", name: "smiling face with horns", keywords: ["devil", "evil"] },
      { char: "💀", name: "skull", keywords: ["death", "dead", "danger"] },
      { char: "👻", name: "ghost", keywords: ["halloween", "spooky", "boo"] },
      { char: "👽", name: "alien", keywords: ["ufo", "extraterrestrial"] },
      { char: "🤖", name: "robot", keywords: ["bot", "machine", "ai"] },
      { char: "💩", name: "pile of poo", keywords: ["poop", "crap"] },
      { char: "🤡", name: "clown face", keywords: ["clown", "joker"] },
      { char: "🙈", name: "see-no-evil monkey", keywords: ["hide", "oops"] },
      { char: "🙉", name: "hear-no-evil monkey", keywords: ["ignore", "deaf"] },
      { char: "🙊", name: "speak-no-evil monkey", keywords: ["secret", "quiet"] },
    ],
  },
  {
    id: "people",
    emoji: [
      { char: "👋", name: "waving hand", keywords: ["wave", "hello", "hi", "goodbye"] },
      { char: "✋", name: "raised hand", keywords: ["stop", "high five"] },
      { char: "🖖", name: "vulcan salute", keywords: ["spock", "star trek"] },
      { char: "👌", name: "ok hand", keywords: ["ok", "perfect"] },
      { char: "🤌", name: "pinched fingers", keywords: ["chef kiss", "italian"] },
      { char: "✌️", name: "victory hand", keywords: ["peace", "two"] },
      { char: "🤞", name: "crossed fingers", keywords: ["luck", "hope"] },
      { char: "🤟", name: "love-you gesture", keywords: ["love", "rock"] },
      { char: "🤘", name: "sign of the horns", keywords: ["rock", "metal"] },
      { char: "🤙", name: "call me hand", keywords: ["call", "hang loose"] },
      { char: "👈", name: "backhand index pointing left", keywords: ["left", "point"] },
      { char: "👉", name: "backhand index pointing right", keywords: ["right", "point"] },
      { char: "👆", name: "backhand index pointing up", keywords: ["up", "point"] },
      { char: "👇", name: "backhand index pointing down", keywords: ["down", "point"] },
      { char: "☝️", name: "index pointing up", keywords: ["one", "attention"] },
      { char: "👍", name: "thumbs up", keywords: ["like", "yes", "approve", "ok"] },
      { char: "👎", name: "thumbs down", keywords: ["dislike", "no"] },
      { char: "✊", name: "raised fist", keywords: ["power", "protest"] },
      { char: "👊", name: "oncoming fist", keywords: ["punch", "fist bump"] },
      { char: "👏", name: "clapping hands", keywords: ["applause", "bravo", "congratulations"] },
      { char: "🙌", name: "raising hands", keywords: ["hooray", "celebration", "praise"] },
      { char: "🤝", name: "handshake", keywords: ["deal", "agreement", "partnership"] },
      { char: "🙏", name: "folded hands", keywords: ["please", "thanks", "pray", "hope"] },
      { char: "✍️", name: "writing hand", keywords: ["write", "signature"] },
      { char: "💅", name: "nail polish", keywords: ["manicure", "sassy"] },
      { char: "💪", name: "flexed biceps", keywords: ["muscle", "strong", "gym", "strength"] },
      { char: "👂", name: "ear", keywords: ["hear", "listen"] },
      { char: "👃", name: "nose", keywords: ["smell"] },
      { char: "🧠", name: "brain", keywords: ["smart", "mind", "intelligence", "idea"] },
      { char: "👀", name: "eyes", keywords: ["look", "watch", "see", "review"] },
      { char: "👶", name: "baby", keywords: ["infant", "newborn"] },
      { char: "🧑", name: "person", keywords: ["adult", "human"] },
      { char: "👨", name: "man", keywords: ["male"] },
      { char: "👩", name: "woman", keywords: ["female"] },
      { char: "🧓", name: "older person", keywords: ["elderly", "senior"] },
      { char: "👮", name: "police officer", keywords: ["police", "cop"] },
      { char: "🕵️", name: "detective", keywords: ["spy", "investigate", "sherlock"] },
      { char: "👷", name: "construction worker", keywords: ["builder", "helmet"] },
      { char: "👸", name: "princess", keywords: ["crown", "royal"] },
      { char: "🦸", name: "superhero", keywords: ["hero", "power"] },
      { char: "🧙", name: "mage", keywords: ["wizard", "magic"] },
      { char: "🧛", name: "vampire", keywords: ["dracula"] },
      { char: "🧟", name: "zombie", keywords: ["undead"] },
      { char: "🚶", name: "person walking", keywords: ["walk", "stroll"] },
      { char: "🏃", name: "person running", keywords: ["run", "sprint", "hurry", "exercise"] },
      { char: "💃", name: "woman dancing", keywords: ["dance", "salsa"] },
      { char: "🕺", name: "man dancing", keywords: ["dance", "disco"] },
      { char: "🧘", name: "person in lotus position", keywords: ["meditation", "yoga", "zen", "calm"] },
      { char: "👨‍💻", name: "man technologist", keywords: ["developer", "programmer", "coder"] },
      { char: "👩‍💻", name: "woman technologist", keywords: ["developer", "programmer", "coder"] },
      { char: "👤", name: "bust in silhouette", keywords: ["user", "profile", "account"] },
      { char: "👥", name: "busts in silhouette", keywords: ["users", "group", "team"] },
      { char: "👪", name: "family", keywords: ["parents", "child"] },
    ],
  },
  {
    id: "animals",
    emoji: [
      { char: "🐶", name: "dog face", keywords: ["dog", "puppy", "pet"] },
      { char: "🐱", name: "cat face", keywords: ["cat", "kitten", "pet"] },
      { char: "🐰", name: "rabbit face", keywords: ["bunny", "rabbit"] },
      { char: "🦊", name: "fox", keywords: ["clever"] },
      { char: "🐻", name: "bear" },
      { char: "🐼", name: "panda" },
      { char: "🐨", name: "koala" },
      { char: "🐯", name: "tiger face", keywords: ["tiger"] },
      { char: "🦁", name: "lion" },
      { char: "🐮", name: "cow face", keywords: ["cow"] },
      { char: "🐷", name: "pig face", keywords: ["pig"] },
      { char: "🐸", name: "frog", keywords: ["toad"] },
      { char: "🐵", name: "monkey face", keywords: ["monkey", "ape"] },
      { char: "🐧", name: "penguin" },
      { char: "🐦", name: "bird", keywords: ["tweet"] },
      { char: "🦆", name: "duck" },
      { char: "🦉", name: "owl", keywords: ["wise", "night"] },
      { char: "🐴", name: "horse face", keywords: ["horse", "pony"] },
      { char: "🦄", name: "unicorn", keywords: ["magic", "fantasy", "rare"] },
      { char: "🐝", name: "honeybee", keywords: ["bee", "buzz"] },
      { char: "🐛", name: "bug", keywords: ["insect", "caterpillar"] },
      { char: "🦋", name: "butterfly" },
      { char: "🐌", name: "snail", keywords: ["slow"] },
      { char: "🕷️", name: "spider", keywords: ["web"] },
      { char: "🐢", name: "turtle", keywords: ["slow", "tortoise"] },
      { char: "🐍", name: "snake", keywords: ["python", "serpent"] },
      { char: "🐙", name: "octopus" },
      { char: "🦀", name: "crab" },
      { char: "🐠", name: "tropical fish", keywords: ["fish", "aquarium"] },
      { char: "🐟", name: "fish" },
      { char: "🐬", name: "dolphin" },
      { char: "🐳", name: "spouting whale", keywords: ["whale"] },
      { char: "🦈", name: "shark" },
      { char: "🐘", name: "elephant" },
      { char: "🐾", name: "paw prints", keywords: ["paws", "tracks", "pet"] },
      { char: "🌵", name: "cactus", keywords: ["desert"] },
      { char: "🌲", name: "evergreen tree", keywords: ["tree", "forest", "pine"] },
      { char: "🌳", name: "deciduous tree", keywords: ["tree", "nature"] },
      { char: "🌴", name: "palm tree", keywords: ["beach", "tropical"] },
      { char: "🌱", name: "seedling", keywords: ["plant", "sprout", "growth", "new"] },
      { char: "🍀", name: "four leaf clover", keywords: ["luck", "clover"] },
      { char: "🍁", name: "maple leaf", keywords: ["autumn", "fall"] },
      { char: "🌹", name: "rose", keywords: ["flower", "love"] },
      { char: "🌸", name: "cherry blossom", keywords: ["flower", "spring"] },
      { char: "🌻", name: "sunflower", keywords: ["flower"] },
      { char: "🍄", name: "mushroom", keywords: ["fungus"] },
      { char: "☀️", name: "sun", keywords: ["sunny", "weather", "bright"] },
      { char: "☁️", name: "cloud", keywords: ["cloudy", "weather"] },
      { char: "🌧️", name: "cloud with rain", keywords: ["rain", "weather"] },
      { char: "❄️", name: "snowflake", keywords: ["snow", "cold", "winter"] },
      { char: "⛄", name: "snowman", keywords: ["snow", "winter"] },
      { char: "🌈", name: "rainbow", keywords: ["colorful", "pride"] },
      { char: "💧", name: "droplet", keywords: ["water", "drop"] },
      { char: "🌊", name: "water wave", keywords: ["ocean", "sea", "wave"] },
      { char: "🔥", name: "fire", keywords: ["flame", "hot", "burn", "lit"] },
      { char: "🌙", name: "crescent moon", keywords: ["moon", "night"] },
    ],
  },
  {
    id: "food",
    emoji: [
      { char: "🍎", name: "red apple", keywords: ["apple", "fruit"] },
      { char: "🍊", name: "tangerine", keywords: ["orange", "fruit"] },
      { char: "🍋", name: "lemon", keywords: ["sour", "citrus"] },
      { char: "🍌", name: "banana" },
      { char: "🍉", name: "watermelon" },
      { char: "🍇", name: "grapes" },
      { char: "🍓", name: "strawberry", keywords: ["berry"] },
      { char: "🍑", name: "peach" },
      { char: "🍍", name: "pineapple" },
      { char: "🍅", name: "tomato" },
      { char: "🥑", name: "avocado", keywords: ["guacamole"] },
      { char: "🥦", name: "broccoli", keywords: ["vegetable"] },
      { char: "🥕", name: "carrot", keywords: ["vegetable"] },
      { char: "🌽", name: "ear of corn", keywords: ["corn", "maize"] },
      { char: "🌶️", name: "hot pepper", keywords: ["spicy", "chili"] },
      { char: "🍞", name: "bread", keywords: ["loaf", "toast"] },
      { char: "🥐", name: "croissant", keywords: ["breakfast", "french"] },
      { char: "🧀", name: "cheese wedge", keywords: ["cheese"] },
      { char: "🥚", name: "egg" },
      { char: "🍳", name: "cooking", keywords: ["fried egg", "breakfast"] },
      { char: "🥞", name: "pancakes", keywords: ["breakfast"] },
      { char: "🍗", name: "poultry leg", keywords: ["chicken", "drumstick"] },
      { char: "🌭", name: "hot dog" },
      { char: "🍔", name: "hamburger", keywords: ["burger", "fast food"] },
      { char: "🍟", name: "french fries", keywords: ["fries", "fast food"] },
      { char: "🍕", name: "pizza", keywords: ["slice"] },
      { char: "🥪", name: "sandwich" },
      { char: "🌮", name: "taco", keywords: ["mexican"] },
      { char: "🥗", name: "green salad", keywords: ["salad", "healthy"] },
      { char: "🍝", name: "spaghetti", keywords: ["pasta", "noodles"] },
      { char: "🍜", name: "steaming bowl", keywords: ["ramen", "noodles", "soup"] },
      { char: "🍣", name: "sushi", keywords: ["japanese"] },
      { char: "🍚", name: "cooked rice", keywords: ["rice"] },
      { char: "🍦", name: "soft ice cream", keywords: ["ice cream", "dessert"] },
      { char: "🍩", name: "doughnut", keywords: ["donut", "dessert"] },
      { char: "🍪", name: "cookie", keywords: ["biscuit"] },
      { char: "🎂", name: "birthday cake", keywords: ["birthday", "celebration", "cake"] },
      { char: "🍰", name: "shortcake", keywords: ["cake", "dessert"] },
      { char: "🧁", name: "cupcake", keywords: ["dessert"] },
      { char: "🍫", name: "chocolate bar", keywords: ["chocolate", "sweet"] },
      { char: "🍬", name: "candy", keywords: ["sweet"] },
      { char: "🍭", name: "lollipop", keywords: ["candy"] },
      { char: "🍿", name: "popcorn", keywords: ["movie", "snack"] },
      { char: "☕", name: "hot beverage", keywords: ["coffee", "tea", "espresso"] },
      { char: "🍵", name: "teacup without handle", keywords: ["tea", "green tea"] },
      { char: "🥛", name: "glass of milk", keywords: ["milk"] },
      { char: "🍺", name: "beer mug", keywords: ["beer"] },
      { char: "🍻", name: "clinking beer mugs", keywords: ["cheers", "beer"] },
      { char: "🥂", name: "clinking glasses", keywords: ["toast", "celebration", "champagne"] },
      { char: "🍷", name: "wine glass", keywords: ["wine"] },
      { char: "🍸", name: "cocktail glass", keywords: ["cocktail", "martini"] },
      { char: "🍾", name: "bottle with popping cork", keywords: ["champagne", "celebration"] },
    ],
  },
  {
    id: "activities",
    emoji: [
      { char: "⚽", name: "soccer ball", keywords: ["football", "soccer"] },
      { char: "🏀", name: "basketball" },
      { char: "🏈", name: "american football", keywords: ["football"] },
      { char: "⚾", name: "baseball" },
      { char: "🎾", name: "tennis" },
      { char: "🏐", name: "volleyball" },
      { char: "🎱", name: "pool 8 ball", keywords: ["billiards", "eight ball"] },
      { char: "🏓", name: "ping pong", keywords: ["table tennis"] },
      { char: "⛳", name: "flag in hole", keywords: ["golf"] },
      { char: "🏹", name: "bow and arrow", keywords: ["archery", "aim"] },
      { char: "🎣", name: "fishing pole", keywords: ["fishing"] },
      { char: "🥊", name: "boxing glove", keywords: ["boxing", "fight"] },
      { char: "🎿", name: "skis", keywords: ["ski", "winter sport"] },
      { char: "🚴", name: "person biking", keywords: ["cycling", "bike"] },
      { char: "🏊", name: "person swimming", keywords: ["swim", "pool"] },
      { char: "🧗", name: "person climbing", keywords: ["climbing", "bouldering"] },
      { char: "🤸", name: "person cartwheeling", keywords: ["gymnastics"] },
      { char: "🏋️", name: "person lifting weights", keywords: ["gym", "workout", "weights", "fitness"] },
      { char: "🏆", name: "trophy", keywords: ["win", "award", "champion", "prize", "success"] },
      { char: "🥇", name: "1st place medal", keywords: ["gold", "first", "winner"] },
      { char: "🥈", name: "2nd place medal", keywords: ["silver", "second"] },
      { char: "🥉", name: "3rd place medal", keywords: ["bronze", "third"] },
      { char: "🏅", name: "sports medal", keywords: ["medal", "award"] },
      { char: "🎫", name: "ticket", keywords: ["admission", "event"] },
      { char: "🎭", name: "performing arts", keywords: ["theater", "drama", "masks"] },
      { char: "🎨", name: "artist palette", keywords: ["art", "paint", "design", "creative"] },
      { char: "🎬", name: "clapper board", keywords: ["movie", "film", "action", "video"] },
      { char: "🎤", name: "microphone", keywords: ["sing", "karaoke", "speech"] },
      { char: "🎧", name: "headphone", keywords: ["music", "audio", "listen"] },
      { char: "🎹", name: "musical keyboard", keywords: ["piano", "keys"] },
      { char: "🥁", name: "drum", keywords: ["drums", "beat"] },
      { char: "🎷", name: "saxophone", keywords: ["sax", "jazz"] },
      { char: "🎸", name: "guitar", keywords: ["rock", "music"] },
      { char: "🎲", name: "game die", keywords: ["dice", "random", "board game"] },
      { char: "🎯", name: "bullseye", keywords: ["dart", "target", "goal", "aim", "focus"] },
      { char: "🎳", name: "bowling", keywords: ["strike"] },
      { char: "🎮", name: "video game", keywords: ["gaming", "controller", "play"] },
      { char: "🕹️", name: "joystick", keywords: ["arcade", "gaming"] },
      { char: "🧩", name: "puzzle piece", keywords: ["jigsaw", "puzzle", "piece"] },
      { char: "🎉", name: "party popper", keywords: ["party", "celebration", "tada", "confetti", "hooray"] },
      { char: "🎊", name: "confetti ball", keywords: ["confetti", "celebration"] },
      { char: "🎈", name: "balloon", keywords: ["party", "birthday"] },
      { char: "🎁", name: "wrapped gift", keywords: ["present", "gift", "birthday", "surprise"] },
      { char: "🎀", name: "ribbon", keywords: ["bow", "gift"] },
      { char: "🎃", name: "jack-o-lantern", keywords: ["halloween", "pumpkin"] },
      { char: "🎄", name: "christmas tree", keywords: ["christmas", "holiday"] },
      { char: "🎆", name: "fireworks", keywords: ["celebration", "new year"] },
      { char: "🧨", name: "firecracker", keywords: ["dynamite", "explosive"] },
    ],
  },
  {
    id: "travel",
    emoji: [
      { char: "🚗", name: "automobile", keywords: ["car", "drive", "vehicle"] },
      { char: "🚕", name: "taxi", keywords: ["cab"] },
      { char: "🚌", name: "bus", keywords: ["transit"] },
      { char: "🏎️", name: "racing car", keywords: ["race", "fast", "formula"] },
      { char: "🚓", name: "police car", keywords: ["police"] },
      { char: "🚑", name: "ambulance", keywords: ["emergency", "medical"] },
      { char: "🚒", name: "fire engine", keywords: ["firetruck", "emergency"] },
      { char: "🚚", name: "delivery truck", keywords: ["truck", "shipping", "transport"] },
      { char: "🚲", name: "bicycle", keywords: ["bike", "cycling"] },
      { char: "🚨", name: "police car light", keywords: ["siren", "alert", "emergency", "alarm"] },
      { char: "⛽", name: "fuel pump", keywords: ["gas", "petrol", "station"] },
      { char: "🚧", name: "construction", keywords: ["barrier", "roadwork", "wip"] },
      { char: "🚂", name: "locomotive", keywords: ["train", "steam", "railway"] },
      { char: "🚄", name: "high-speed train", keywords: ["train", "bullet", "fast"] },
      { char: "🚆", name: "train", keywords: ["railway", "transit"] },
      { char: "🚇", name: "metro", keywords: ["subway", "underground"] },
      { char: "✈️", name: "airplane", keywords: ["flight", "plane", "travel", "trip"] },
      { char: "🛫", name: "airplane departure", keywords: ["takeoff", "departure"] },
      { char: "🛬", name: "airplane arrival", keywords: ["landing", "arrival"] },
      { char: "🚁", name: "helicopter", keywords: ["chopper"] },
      { char: "🚀", name: "rocket", keywords: ["launch", "space", "ship", "startup", "fast"] },
      { char: "🛸", name: "flying saucer", keywords: ["ufo", "alien"] },
      { char: "🛰️", name: "satellite", keywords: ["space", "orbit"] },
      { char: "⛵", name: "sailboat", keywords: ["sailing", "boat", "yacht"] },
      { char: "🚤", name: "speedboat", keywords: ["boat", "fast"] },
      { char: "⚓", name: "anchor", keywords: ["harbor", "port", "ship"] },
      { char: "🚢", name: "ship", keywords: ["boat", "cruise"] },
      { char: "🗺️", name: "world map", keywords: ["map", "atlas", "geography"] },
      { char: "🧭", name: "compass", keywords: ["navigation", "direction", "orientation"] },
      { char: "🌍", name: "globe showing europe-africa", keywords: ["earth", "world", "globe", "planet"] },
      { char: "🌎", name: "globe showing americas", keywords: ["earth", "world", "globe"] },
      { char: "🌏", name: "globe showing asia-australia", keywords: ["earth", "world", "globe"] },
      { char: "🌐", name: "globe with meridians", keywords: ["internet", "web", "www", "global", "network"] },
      { char: "🏔️", name: "snow-capped mountain", keywords: ["mountain", "alps", "peak"] },
      { char: "🌋", name: "volcano", keywords: ["eruption", "lava"] },
      { char: "🏕️", name: "camping", keywords: ["tent", "campsite", "outdoor"] },
      { char: "⛺", name: "tent", keywords: ["camping"] },
      { char: "🏖️", name: "beach with umbrella", keywords: ["beach", "vacation", "holiday"] },
      { char: "🏝️", name: "desert island", keywords: ["island", "vacation"] },
      { char: "🎢", name: "roller coaster", keywords: ["amusement park", "fun"] },
      { char: "🗽", name: "statue of liberty", keywords: ["new york", "usa", "liberty"] },
      { char: "🗼", name: "tokyo tower", keywords: ["tower", "landmark"] },
      { char: "🏰", name: "castle", keywords: ["fortress", "fairy tale", "palace"] },
      { char: "🗿", name: "moai", keywords: ["statue", "easter island", "stone"] },
      { char: "🏠", name: "house", keywords: ["home", "building"] },
      { char: "🏡", name: "house with garden", keywords: ["home", "house"] },
      { char: "🏢", name: "office building", keywords: ["office", "work", "company", "building"] },
      { char: "🏗️", name: "building construction", keywords: ["crane", "construction", "site"] },
      { char: "🏭", name: "factory", keywords: ["industry", "production"] },
      { char: "🏥", name: "hospital", keywords: ["medical", "health", "clinic"] },
      { char: "🏦", name: "bank", keywords: ["money", "finance"] },
      { char: "🏫", name: "school", keywords: ["education", "university"] },
      { char: "🌉", name: "bridge at night", keywords: ["bridge"] },
      { char: "🌅", name: "sunrise", keywords: ["morning", "dawn"] },
    ],
  },
  {
    id: "objects",
    emoji: [
      { char: "📱", name: "mobile phone", keywords: ["smartphone", "phone", "cell"] },
      { char: "💻", name: "laptop", keywords: ["computer", "notebook", "pc", "mac"] },
      { char: "⌨️", name: "keyboard", keywords: ["typing", "keys"] },
      { char: "🖥️", name: "desktop computer", keywords: ["computer", "monitor", "pc", "screen"] },
      { char: "🖨️", name: "printer", keywords: ["print"] },
      { char: "💾", name: "floppy disk", keywords: ["save", "disk", "storage"] },
      { char: "📷", name: "camera", keywords: ["photo", "photography", "picture"] },
      { char: "🎥", name: "movie camera", keywords: ["film", "cinema", "video"] },
      { char: "📞", name: "telephone receiver", keywords: ["call", "phone", "contact"] },
      { char: "📺", name: "television", keywords: ["tv", "screen"] },
      { char: "⏰", name: "alarm clock", keywords: ["alarm", "morning", "wake", "time"] },
      { char: "⏳", name: "hourglass not done", keywords: ["time", "waiting", "loading", "patience"] },
      { char: "🔋", name: "battery", keywords: ["power", "energy", "charge"] },
      { char: "🔌", name: "electric plug", keywords: ["power", "plug", "electricity"] },
      { char: "💡", name: "light bulb", keywords: ["idea", "tip", "bright", "insight"] },
      { char: "🗑️", name: "wastebasket", keywords: ["trash", "delete", "bin", "garbage"] },
      { char: "💵", name: "dollar banknote", keywords: ["money", "cash", "dollar"] },
      { char: "💰", name: "money bag", keywords: ["money", "cash", "rich", "budget"] },
      { char: "💳", name: "credit card", keywords: ["payment", "card", "finance"] },
      { char: "💎", name: "gem stone", keywords: ["diamond", "jewel", "precious", "value"] },
      { char: "⚖️", name: "balance scale", keywords: ["justice", "law", "balance", "compare"] },
      { char: "🧰", name: "toolbox", keywords: ["tools", "repair", "kit"] },
      { char: "🔧", name: "wrench", keywords: ["tool", "fix", "repair"] },
      { char: "🔨", name: "hammer", keywords: ["tool", "build"] },
      { char: "🛠️", name: "hammer and wrench", keywords: ["tools", "settings", "repair", "maintenance"] },
      { char: "⚙️", name: "gear", keywords: ["settings", "config", "cog", "preferences", "setup"] },
      { char: "🔮", name: "crystal ball", keywords: ["magic", "fortune", "future", "prediction"] },
      { char: "🔭", name: "telescope", keywords: ["astronomy", "stars", "explore"] },
      { char: "🔬", name: "microscope", keywords: ["science", "research", "lab", "detail"] },
      { char: "💊", name: "pill", keywords: ["medicine", "drug", "pharmacy", "health"] },
      { char: "🧬", name: "dna", keywords: ["genetics", "biology", "science"] },
      { char: "🧪", name: "test tube", keywords: ["experiment", "chemistry", "lab", "science", "test"] },
      { char: "🛡️", name: "shield", keywords: ["security", "protection", "defense", "safety"] },
      { char: "🛒", name: "shopping cart", keywords: ["cart", "buy", "shopping", "purchase"] },
      { char: "👑", name: "crown", keywords: ["king", "queen", "royal", "best"] },
      { char: "📕", name: "closed book", keywords: ["book", "red"] },
      { char: "📖", name: "open book", keywords: ["book", "read", "reading"] },
      { char: "📗", name: "green book", keywords: ["book"] },
      { char: "📘", name: "blue book", keywords: ["book"] },
      { char: "📙", name: "orange book", keywords: ["book"] },
      { char: "📚", name: "books", keywords: ["library", "reading", "study", "knowledge", "documentation"] },
      { char: "📓", name: "notebook", keywords: ["journal", "notes"] },
      { char: "📜", name: "scroll", keywords: ["document", "ancient", "certificate"] },
      { char: "📄", name: "page facing up", keywords: ["document", "file", "page", "paper"] },
      { char: "📰", name: "newspaper", keywords: ["news", "press", "article"] },
      { char: "🔖", name: "bookmark", keywords: ["tag", "marker", "favorite"] },
      { char: "🏷️", name: "label", keywords: ["tag", "price", "category"] },
      { char: "✉️", name: "envelope", keywords: ["mail", "email", "letter", "message"] },
      { char: "📧", name: "e-mail", keywords: ["email", "mail", "message"] },
      { char: "📤", name: "outbox tray", keywords: ["send", "outbox", "upload"] },
      { char: "📥", name: "inbox tray", keywords: ["receive", "inbox", "download"] },
      { char: "📦", name: "package", keywords: ["box", "shipping", "delivery", "parcel", "module"] },
      { char: "✏️", name: "pencil", keywords: ["write", "edit", "draw"] },
      { char: "📝", name: "memo", keywords: ["note", "notes", "write", "todo", "draft"] },
      { char: "📁", name: "file folder", keywords: ["folder", "directory"] },
      { char: "📂", name: "open file folder", keywords: ["folder", "open", "directory"] },
      { char: "🗂️", name: "card index dividers", keywords: ["folders", "organize", "categories", "index"] },
      { char: "📅", name: "calendar", keywords: ["date", "schedule", "plan"] },
      { char: "📈", name: "chart increasing", keywords: ["graph", "growth", "up", "stats", "trending"] },
      { char: "📉", name: "chart decreasing", keywords: ["graph", "decline", "down", "loss"] },
      { char: "📊", name: "bar chart", keywords: ["statistics", "data", "analytics", "chart", "metrics"] },
      { char: "📋", name: "clipboard", keywords: ["tasks", "checklist", "copy", "list"] },
      { char: "📌", name: "pushpin", keywords: ["pin", "tack", "important"] },
      { char: "📍", name: "round pushpin", keywords: ["location", "pin", "place", "marker"] },
      { char: "📎", name: "paperclip", keywords: ["attachment", "clip"] },
      { char: "📏", name: "straight ruler", keywords: ["measure", "ruler", "length"] },
      { char: "✂️", name: "scissors", keywords: ["cut", "snip"] },
      { char: "🗄️", name: "file cabinet", keywords: ["archive", "storage", "files"] },
      { char: "🔒", name: "locked", keywords: ["lock", "secure", "private", "password", "security"] },
      { char: "🔓", name: "unlocked", keywords: ["unlock", "open", "public"] },
      { char: "🔑", name: "key", keywords: ["password", "access", "unlock", "secret"] },
      { char: "🔗", name: "link", keywords: ["chain", "url", "connection", "hyperlink"] },
      { char: "📢", name: "loudspeaker", keywords: ["announcement", "megaphone", "broadcast"] },
      { char: "🔔", name: "bell", keywords: ["notification", "alarm", "reminder", "alert"] },
      { char: "🔍", name: "magnifying glass tilted left", keywords: ["search", "find", "zoom", "lookup"] },
    ],
  },
  {
    id: "symbols",
    emoji: [
      { char: "❤️", name: "red heart", keywords: ["love", "heart"] },
      { char: "🧡", name: "orange heart", keywords: ["heart"] },
      { char: "💛", name: "yellow heart", keywords: ["heart"] },
      { char: "💚", name: "green heart", keywords: ["heart"] },
      { char: "💙", name: "blue heart", keywords: ["heart"] },
      { char: "💜", name: "purple heart", keywords: ["heart"] },
      { char: "🖤", name: "black heart", keywords: ["heart", "dark"] },
      { char: "💔", name: "broken heart", keywords: ["heartbreak", "sad"] },
      { char: "💕", name: "two hearts", keywords: ["love", "hearts"] },
      { char: "💯", name: "hundred points", keywords: ["100", "perfect", "score", "top"] },
      { char: "💥", name: "collision", keywords: ["boom", "explosion", "crash", "impact"] },
      { char: "⭐", name: "star", keywords: ["favorite", "rating"] },
      { char: "🌟", name: "glowing star", keywords: ["star", "shining", "awesome"] },
      { char: "✨", name: "sparkles", keywords: ["magic", "new", "shiny", "clean", "highlight"] },
      { char: "⚡", name: "high voltage", keywords: ["lightning", "zap", "energy", "power", "fast"] },
      { char: "♻️", name: "recycling symbol", keywords: ["recycle", "green", "sustainability"] },
      { char: "✅", name: "check mark button", keywords: ["done", "complete", "yes", "check", "todo", "success"] },
      { char: "☑️", name: "check box with check", keywords: ["checkbox", "done", "task"] },
      { char: "✔️", name: "check mark", keywords: ["done", "yes", "check", "confirmed"] },
      { char: "❌", name: "cross mark", keywords: ["x", "no", "wrong", "delete", "error"] },
      { char: "➕", name: "plus", keywords: ["add", "new", "math"] },
      { char: "➖", name: "minus", keywords: ["subtract", "remove", "math"] },
      { char: "❓", name: "question mark", keywords: ["question", "help", "faq"] },
      { char: "❗", name: "exclamation mark", keywords: ["important", "warning", "attention"] },
      { char: "⚠️", name: "warning", keywords: ["caution", "alert", "attention", "danger"] },
      { char: "⛔", name: "no entry", keywords: ["forbidden", "stop", "blocked"] },
      { char: "🚫", name: "prohibited", keywords: ["ban", "forbidden", "no", "blocked"] },
      { char: "💤", name: "zzz", keywords: ["sleep", "tired", "snore"] },
      { char: "🎵", name: "musical note", keywords: ["music", "note", "song"] },
      { char: "🔴", name: "red circle", keywords: ["red", "dot", "record"] },
      { char: "🟠", name: "orange circle", keywords: ["orange", "dot"] },
      { char: "🟡", name: "yellow circle", keywords: ["yellow", "dot"] },
      { char: "🟢", name: "green circle", keywords: ["green", "dot", "online", "active"] },
      { char: "🔵", name: "blue circle", keywords: ["blue", "dot"] },
      { char: "🟣", name: "purple circle", keywords: ["purple", "dot"] },
      { char: "⚫", name: "black circle", keywords: ["black", "dot"] },
      { char: "⚪", name: "white circle", keywords: ["white", "dot"] },
      { char: "⬛", name: "black large square", keywords: ["black", "square"] },
      { char: "⬜", name: "white large square", keywords: ["white", "square"] },
      { char: "⬆️", name: "up arrow", keywords: ["up", "north", "increase"] },
      { char: "⬇️", name: "down arrow", keywords: ["down", "south", "decrease"] },
      { char: "⬅️", name: "left arrow", keywords: ["left", "back", "previous"] },
      { char: "➡️", name: "right arrow", keywords: ["right", "next", "forward"] },
      { char: "↩️", name: "right arrow curving left", keywords: ["reply", "undo", "return", "back"] },
      { char: "↪️", name: "left arrow curving right", keywords: ["redo", "forward"] },
      { char: "🔄", name: "counterclockwise arrows button", keywords: ["refresh", "sync", "reload", "update"] },
      { char: "🔁", name: "repeat button", keywords: ["loop", "repeat", "again"] },
      { char: "▶️", name: "play button", keywords: ["play", "start", "resume"] },
      { char: "⏸️", name: "pause button", keywords: ["pause", "hold"] },
      { char: "ℹ️", name: "information", keywords: ["info", "about", "details"] },
      { char: "🆕", name: "new button", keywords: ["new", "fresh"] },
      { char: "🏁", name: "chequered flag", keywords: ["finish", "race", "done", "goal", "complete"] },
      { char: "🚩", name: "triangular flag", keywords: ["flag", "milestone", "report", "marker"] },
      { char: "🏳️‍🌈", name: "rainbow flag", keywords: ["pride", "lgbt", "rainbow"] },
    ],
  },
];

const MAX_RESULTS = 60;

export function searchEmoji(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const results: EmojiEntry[] = [];
  const seen = new Set<string>();
  for (const category of EMOJI_CATEGORIES) {
    for (const entry of category.emoji) {
      if (results.length >= MAX_RESULTS) return results;
      if (seen.has(entry.char)) continue;
      const matches =
        entry.name.toLowerCase().includes(q) ||
        (entry.keywords?.some((k) => k.toLowerCase().includes(q)) ?? false);
      if (matches) {
        seen.add(entry.char);
        results.push(entry);
      }
    }
  }
  return results;
}
