import React, { useState } from "react";
import { open } from "@tauri-apps/plugin-dialog";
import { Banner, Button, Modal, Select, SettingCardNote, SettingRow, TextInput } from "@plainva/ui";
import { useTranslation } from "react-i18next";
import { providerOptions, roleOptions, type Governance, type GovernanceForm } from "./securityForms";

/**
 * Governance dialog for the encrypted-workspace security centre. Split out of
 * SecuritySharingPage (package B3). All pickers use the themed Select primitive
 * — the OS-rendered native dropdown popups are gone (package B2).
 */
export const WorkspaceGovernanceDialog: React.FC<{
  kind: "pair" | "invite" | "group" | "slice" | "recovery" | "rotate" | "owner";
  busy: boolean;
  form: GovernanceForm;
  governance: Governance | null;
  pairPreview: { token: string; deviceName: string; platform: string; memberId: string; fingerprint: string; expiresAt: string } | null;
  slicePreview: Array<{ objectId: string; path: string }> | null;
  rotatedRecoveryCode: string | null;
  setForm: React.Dispatch<React.SetStateAction<GovernanceForm>>;
  onClose: () => void;
  onPreview: () => void;
  onSubmit: () => void;
}> = ({ kind, busy, form, governance, pairPreview, slicePreview, rotatedRecoveryCode, setForm, onClose, onPreview, onSubmit }) => {
  const { t } = useTranslation();
  const [sliceStep, setSliceStep] = useState<1 | 2 | 3 | 4>(1);
  const update = (patch: Partial<GovernanceForm>) => setForm((current) => ({ ...current, ...patch }));
  const scopeOptions = [
    { value: "workspace", label: t("workspaceSecurity.wholeWorkspace", { defaultValue: "Whole workspace" }) },
    { value: "slice", label: t("workspaceSecurity.slice", { defaultValue: "Slice" }) },
    { value: "object", label: t("workspaceSecurity.singleObject", { defaultValue: "Single object" }) },
  ];
  const sliceScopeOptions = (governance?.slices ?? []).map((slice) => ({ value: slice.sliceId, label: slice.name }));
  const ownerCandidateOptions = (governance?.members ?? [])
    .filter((member) => member.state === "active" && member.memberId !== governance?.memberId)
    .map((member) => ({ value: member.memberId, label: member.displayName }));
  const title = kind === "pair" ? t("workspaceSecurity.pairDevice", { defaultValue: "Approve device" })
    : kind === "invite" ? t("workspaceSecurity.invite", { defaultValue: "Invite member" })
      : kind === "group" ? t("workspaceSecurity.addGroup", { defaultValue: "Add group" })
        : kind === "slice" ? t("workspaceSecurity.addSlice", { defaultValue: "Add slice" })
          : kind === "rotate" ? t("workspaceSecurity.rotateRecovery", { defaultValue: "Renew recovery" })
            : kind === "owner" ? t("workspaceSecurity.transferOwner", { defaultValue: "Transfer ownership" })
            : t("workspaceSecurity.restore", { defaultValue: "Restore access" });
  return (
    <Modal title={title} onClose={() => { if (!busy) onClose(); }} size="md">
      <div className="pv-security-wizard">
        {kind === "pair" && <><Banner kind="info" rounded>{t("workspaceSecurity.pairHelp", { defaultValue: "Paste the QR token or enter the manual code shown on the new device. Verify its fingerprint before approving." })}</Banner>{pairPreview ? <><SettingRow label={pairPreview.deviceName} desc={`${pairPreview.platform} · ${pairPreview.memberId}`}><span>{new Date(pairPreview.expiresAt).toLocaleString()}</span></SettingRow><label className="pv-security-field"><span>{t("workspaceSecurity.fingerprint", { defaultValue: "Fingerprint" })}</span><code className="pv-security-code">{pairPreview.fingerprint}</code></label><Banner kind="warning" rounded>{t("workspaceSecurity.compareFingerprint", { defaultValue: "Approve only if this fingerprint exactly matches the one displayed on the new device." })}</Banner></> : <label className="pv-security-field"><span>{t("workspaceSecurity.pairCode", { defaultValue: "Token or manual code" })}</span><TextInput autoFocus value={form.code} onChange={(event) => update({ code: event.target.value })} /></label>}</>}
        {(kind === "invite" || kind === "group") && <label className="pv-security-field"><span>{t("workspaceSecurity.name")}</span><TextInput autoFocus value={form.name} onChange={(event) => update({ name: event.target.value })} /></label>}
        {(kind === "invite" || kind === "group") && <div className="pv-security-field"><span>{t("workspaceSecurity.role", { defaultValue: "Role" })}</span><Select value={form.role} options={roleOptions(t)} onChange={(value) => update({ role: value })} ariaLabel={t("workspaceSecurity.role", { defaultValue: "Role" })} /></div>}
        {(kind === "invite" || kind === "group") && <><div className="pv-security-field"><span>{t("workspaceSecurity.scope", { defaultValue: "Scope" })}</span><Select value={form.scopeKind} options={scopeOptions} onChange={(value) => update({ scopeKind: value, scopeId: "" })} ariaLabel={t("workspaceSecurity.scope", { defaultValue: "Scope" })} /></div>{form.scopeKind !== "workspace" && <div className="pv-security-field"><span>{form.scopeKind === "slice" ? t("workspaceSecurity.slice", { defaultValue: "Slice" }) : t("workspaceSecurity.objectId", { defaultValue: "Object ID" })}</span>{form.scopeKind === "slice" ? <Select value={form.scopeId} options={sliceScopeOptions} onChange={(value) => update({ scopeId: value })} ariaLabel={t("workspaceSecurity.slice", { defaultValue: "Slice" })} placeholder="—" /> : <TextInput value={form.scopeId} onChange={(event) => update({ scopeId: event.target.value })} />}</div>}</>}
        {kind === "group" && <><label className="pv-security-field"><span>{t("workspaceSecurity.memberIds", { defaultValue: "Member IDs (comma-separated)" })}</span><TextInput value={form.members} onChange={(event) => update({ members: event.target.value })} /></label><SettingCardNote>{governance?.members.map((member) => `${member.displayName}: ${member.memberId}`).join(" · ")}</SettingCardNote></>}
        {kind === "slice" && <div className="pv-security-slice-wizard">
          <div className="pv-security-steps" aria-label={t("workspaceSecurity.sliceProgress", { defaultValue: "Vault Slice creation progress" })}>{["details", "content", "permissions", "review"].map((value, index) => <span key={value} data-active={sliceStep === index + 1}>{t(`workspaceSecurity.sliceStep.${value}`, { defaultValue: value[0].toUpperCase() + value.slice(1) })}</span>)}</div>
          {sliceStep === 1 && <><label className="pv-security-field"><span>{t("workspaceSecurity.name")}</span><TextInput autoFocus value={form.name} onChange={(event) => update({ name: event.target.value })} /></label><SettingCardNote>{t("workspaceSecurity.sliceDetailsHint", { defaultValue: "Use a name recipients will recognize. The definition can be changed later without changing the slice ID." })}</SettingCardNote></>}
          {sliceStep === 2 && <><div className="pv-security-choice-grid">{(["folder", "selection", "dynamic"] as const).map((value) => <button type="button" className={`pv-security-choice${form.sliceKind === value ? " is-active" : ""}`} key={value} onClick={() => update({ sliceKind: value, definition: "" })}><strong>{t(`workspaceSecurity.slice${value[0].toUpperCase() + value.slice(1)}`)}</strong><span>{t(`workspaceSecurity.sliceKindHint.${value}`, { defaultValue: value === "folder" ? "A folder and optional descendants" : value === "selection" ? "Explicit notes and attachments" : "A materialized rule result" })}</span></button>)}</div><label className="pv-security-field"><span>{form.sliceKind === "folder" ? t("workspaceSecurity.sliceFolderPath") : form.sliceKind === "selection" ? t("workspaceSecurity.sliceObjectIds") : t("workspaceSecurity.sliceRuleJson")}</span><TextInput value={form.definition} onChange={(event) => update({ definition: event.target.value })} /></label><SettingCardNote>{t("workspaceSecurity.slicePreview", { defaultValue: "The preview is calculated against the encrypted local object index before the policy is published." })}</SettingCardNote><Button variant="secondary" disabled={busy || !form.definition.trim()} onClick={onPreview}>{t("workspaceSecurity.preview", { defaultValue: "Preview" })}</Button>{slicePreview && <div className="pv-security-preview"><strong>{t("workspaceSecurity.previewCount", { defaultValue: "{{count}} matching objects", count: slicePreview.length })}</strong>{slicePreview.slice(0, 20).map((entry) => <code key={entry.objectId}>{entry.path}</code>)}</div>}</>}
          {sliceStep === 3 && <><div className="pv-security-field"><span>{t("workspaceSecurity.publicationMode", { defaultValue: "Publication" })}</span><Select value={form.publicationMode} onChange={(value) => update({ publicationMode: value })} ariaLabel={t("workspaceSecurity.publicationMode", { defaultValue: "Publication" })} options={[{ value: "private", label: t("workspaceSecurity.privateSlice", { defaultValue: "Internal Vault Slice" }) }, { value: "exact", label: t("workspaceSecurity.exactPublication", { defaultValue: "Separate exact encrypted publication" }) }, { value: "sanitized", label: t("workspaceSecurity.sanitizedPublication", { defaultValue: "Separate sanitized encrypted publication" }) }]} /></div>{form.publicationMode !== "private" && <><div className="pv-security-field"><span>{t("workspaceSecurity.access", { defaultValue: "Access" })}</span><Select value={form.publicationAccess} onChange={(value) => update({ publicationAccess: value })} ariaLabel={t("workspaceSecurity.access", { defaultValue: "Access" })} options={[{ value: "read", label: t("workspaceSecurity.read", { defaultValue: "Read" }) }, { value: "comment", label: t("workspaceSecurity.comment", { defaultValue: "Comment" }) }, { value: "suggest", label: t("workspaceSecurity.suggest", { defaultValue: "Suggest changes" }) }]} /></div><div className="pv-security-field"><span>{t("workspaceSecurity.provider", { defaultValue: "Provider" })}</span><Select value={form.publicationProvider} onChange={(value) => update({ publicationProvider: value })} ariaLabel={t("workspaceSecurity.provider", { defaultValue: "Provider" })} options={providerOptions()} /></div><Banner kind="info" rounded>{t("workspaceSecurity.providerAclHint", { defaultValue: "Provider permissions are applied as defense in depth. The publication remains a separate encrypted workspace even if the provider ACL fails." })}</Banner></>}</>}
          {sliceStep === 4 && <><Banner kind="info" rounded>{t("workspaceSecurity.sliceReviewHint", { defaultValue: "Review the materialized scope before publishing the signed policy. Excluded links and private properties are scrubbed from sanitized projections." })}</Banner><dl className="pv-security-details"><dt>{t("workspaceSecurity.name")}</dt><dd>{form.name}</dd><dt>{t("workspaceSecurity.sliceKind")}</dt><dd>{form.sliceKind}</dd><dt>{t("workspaceSecurity.preview", { defaultValue: "Preview" })}</dt><dd>{slicePreview?.length ?? 0} objects</dd><dt>{t("workspaceSecurity.publicationMode", { defaultValue: "Publication" })}</dt><dd>{form.publicationMode}{form.publicationMode !== "private" ? ` · ${form.publicationAccess} · ${form.publicationProvider}` : ""}</dd></dl></>}
        </div>}
        {kind === "recovery" && <><Banner kind="warning" rounded>{t("workspaceSecurity.restoreWarning", { defaultValue: "Recovery creates a new owner device and revokes the lost devices. Encrypted content and revision IDs are not rewritten." })}</Banner><SettingRow label={t("workspaceSecurity.recoveryFile", { defaultValue: "Recovery file" })}><Button variant="secondary" onClick={() => void open({ multiple: false, filters: [{ name: "Plainva recovery", extensions: ["pvrecovery"] }] }).then((path) => { if (typeof path === "string") update({ recoveryFile: path }); })}>{form.recoveryFile || t("workspaceSecurity.choose")}</Button></SettingRow><label className="pv-security-field"><span>{t("workspaceSecurity.recoveryCode")}</span><TextInput value={form.recoveryCode} onChange={(event) => update({ recoveryCode: event.target.value })} /></label><label className="pv-security-field"><span>{t("workspaceSecurity.deviceName")}</span><TextInput value={form.deviceName} onChange={(event) => update({ deviceName: event.target.value })} /></label><label className="pv-security-field"><span>{t("workspaceSecurity.fallbackPassphrase")}</span><TextInput type="password" value={form.fallbackPassphrase} onChange={(event) => update({ fallbackPassphrase: event.target.value })} /></label></>}
        {kind === "rotate" && (rotatedRecoveryCode ? <><Banner kind="success" rounded>{t("workspaceSecurity.rotateRecoveryDone", { defaultValue: "The new recovery identity is anchored and the renewed file was saved. Store this new code separately; the old recovery set is no longer accepted." })}</Banner><code className="pv-security-code">{rotatedRecoveryCode}</code><Button variant="ghost" onClick={() => void navigator.clipboard.writeText(rotatedRecoveryCode)}>{t("workspaceSecurity.copyCode")}</Button></> : <><Banner kind="warning" rounded>{t("workspaceSecurity.rotateRecoveryWarning", { defaultValue: "You need the current recovery file and code. A new identity, file and separate code will replace them." })}</Banner><SettingRow label={t("workspaceSecurity.recoveryFile", { defaultValue: "Recovery file" })}><Button variant="secondary" onClick={() => void open({ multiple: false, filters: [{ name: "Plainva recovery", extensions: ["pvrecovery"] }] }).then((path) => { if (typeof path === "string") update({ recoveryFile: path }); })}>{form.recoveryFile || t("workspaceSecurity.choose")}</Button></SettingRow><label className="pv-security-field"><span>{t("workspaceSecurity.recoveryCode")}</span><TextInput value={form.recoveryCode} onChange={(event) => update({ recoveryCode: event.target.value })} /></label></>)}
        {kind === "owner" && (rotatedRecoveryCode ? <><Banner kind="success" rounded>{t("workspaceSecurity.ownerTransferDone", { defaultValue: "Ownership and recovery were transferred. Give the new recovery file and this code to the new owner through separate secure channels." })}</Banner><code className="pv-security-code">{rotatedRecoveryCode}</code><Button variant="ghost" onClick={() => void navigator.clipboard.writeText(rotatedRecoveryCode)}>{t("workspaceSecurity.copyCode")}</Button></> : <><Banner kind="warning" rounded>{t("workspaceSecurity.ownerTransferWarning", { defaultValue: "The new recovery file is saved before the recovery anchor and owner policy activate. You become Admin; the target becomes the only Owner." })}</Banner><div className="pv-security-field"><span>{t("workspaceSecurity.newOwner", { defaultValue: "New owner" })}</span><Select value={form.scopeId} onChange={(value) => update({ scopeId: value })} ariaLabel={t("workspaceSecurity.newOwner", { defaultValue: "New owner" })} placeholder="—" options={ownerCandidateOptions} /></div><SettingRow label={t("workspaceSecurity.recoveryFile")}><Button variant="secondary" onClick={() => void open({ multiple: false, filters: [{ name: "Plainva recovery", extensions: ["pvrecovery"] }] }).then((path) => { if (typeof path === "string") update({ recoveryFile: path }); })}>{form.recoveryFile || t("workspaceSecurity.choose")}</Button></SettingRow><label className="pv-security-field"><span>{t("workspaceSecurity.recoveryCode")}</span><TextInput value={form.recoveryCode} onChange={(event) => update({ recoveryCode: event.target.value })} /></label></>)}
        <div className="pv-security-actions"><Button variant="ghost" disabled={busy} onClick={sliceStep > 1 && kind === "slice" ? () => setSliceStep((sliceStep - 1) as 1 | 2 | 3) : onClose}>{sliceStep > 1 && kind === "slice" ? t("cloudAccounts.back", { defaultValue: "Back" }) : rotatedRecoveryCode ? t("common.close", { defaultValue: "Close" }) : t("common.cancel")}</Button>{!rotatedRecoveryCode && <Button variant="primary" disabled={busy || (kind === "pair" ? !form.code.trim() : (kind === "recovery" || kind === "rotate" || kind === "owner") ? !form.recoveryFile || !form.recoveryCode || (kind === "recovery" && !form.deviceName) || (kind === "owner" && !form.scopeId) : !form.name.trim()) || ((kind === "invite" || kind === "group") && form.scopeKind !== "workspace" && !form.scopeId) || (kind === "slice" && sliceStep >= 2 && !form.definition.trim())} onClick={kind === "slice" && sliceStep < 4 ? () => { if (sliceStep === 2) onPreview(); setSliceStep((sliceStep + 1) as 2 | 3 | 4); } : onSubmit}>{kind === "pair" && !pairPreview ? t("workspaceSecurity.verify", { defaultValue: "Verify" }) : kind === "slice" && sliceStep < 4 ? t("splash.continue", { defaultValue: "Continue" }) : t("common.confirm", { defaultValue: "Confirm" })}</Button>}</div>
      </div>
    </Modal>
  );
};
